(function(){
'use strict';
const $=id=>document.getElementById(id),api=window.BalTransition={active:false};
const row=document.createElement('div');row.className='settings-row';const copy=document.createElement('span');copy.textContent='Aşama testi';const skip=document.createElement('button');skip.id='skipStage';skip.className='team-action';skip.type='button';skip.textContent=LeagueRules.config.bal?'BAL aşamasındasın':'Aşama atla → BAL';skip.disabled=!!LeagueRules.config.bal;row.append(copy,skip);$('settingsDialog').querySelector('.reset-section').before(row);
async function start(test=false){if(api.active||LeagueRules.config.bal||(!test&&!LeagueSeason.progress().prologueComplete))return;api.active=true;
for(const d of document.querySelectorAll('dialog[open]'))d.close();const clubLink=document.querySelector('.mobile-nav a[href="#clubPanel"]');clubLink.addEventListener('click',e=>e.preventDefault(),{once:true});clubLink.click();
const restoreView=BalVisual.capture($('workflow'));const workflow=$('workflow'),dashboard=document.querySelector('.dashboard');dashboard.hidden=false;document.body.classList.add('bal-transforming');
const banner=document.createElement('aside');banner.className='bal-live-banner';banner.setAttribute('role','status');const text=document.createElement('strong');text.textContent='Kulübün BAL için yenileniyor';const note=document.createElement('small');note.textContent='Yeni başlangıç · Daha hızlı gelişim';const end=document.createElement('button');end.textContent='Animasyonu geç';banner.append(text,note,end);$('clubPanel').prepend(banner);const animations=[];let done=false;
function commit(){if(done)return;done=true;let journalWritten=false;try{const room=BalRules.enter(RoomSystem.snapshot(),1),players=TeamRules.players.map(p=>{const q=JSON.parse(JSON.stringify(p));for(const k of TeamRules.trainable)q[k]=Math.max(0,Math.min(50,Number(q.baseStats?.[k])||15));q.art=q.art.startsWith('team-assets/')?q.art:'team-assets/woman-0.svg';q.training={};q.cardLevel=1;q.cardVersion=1;q.skills=(q.skills||[]).map(skill=>({...skill,unlocked:false}));return q});room.lastSeen=Date.now();const entries={'idle-spiker-rooms-v2':JSON.stringify(room),'idle-spiker-women-v1':JSON.stringify(players),'idle-spiker-main-menu-v1':JSON.stringify({day:1,clicksToday:0}),'idle-spiker-league-v1':JSON.stringify({version:3,mode:'bal',run:1,startDay:1,results:{},completionSeen:false,completedDay:null}),'idle-spiker-match-results':JSON.stringify({version:3}),'idle-spiker-onboarding-v1':JSON.stringify(['tap','arrival','blocks-basics','assistant','train','match','quick-upgrade']),'idle-spiker-prologue-archive-v1':JSON.stringify({league:JSON.parse(localStorage.getItem('idle-spiker-league-v1')||'null'),rooms:RoomSystem.snapshot(),players:TeamRules.players})};localStorage.setItem('idle-spiker-bal-transition-v1',JSON.stringify({version:1,entries}));journalWritten=true;window.gameResetting=true;for(const [key,value]of Object.entries(entries))localStorage.setItem(key,value);localStorage.removeItem('idle-spiker-bal-transition-v1');location.reload();}catch{if(journalWritten){location.reload();return}animations.forEach(a=>a.cancel());restoreView();document.body.classList.remove('bal-transforming');for(const tier of workflow.querySelectorAll('.tier')){tier.style.removeProperty('opacity');const f=Number(tier.dataset.floor);tier.querySelector('h3').textContent=RoomRules.departments[f];if(f===4){tier.hidden=true;tier.style.display='none'}}api.active=false;banner.remove();$('settingsDialog').showModal();copy.textContent='Geçiş kaydedilemedi. Yeniden dene.';}}
end.onclick=commit;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
async function animate(el,frames,options){if(done)return;const a=el.animate(frames,{...options,duration:reduced?1:options.duration,fill:'forwards'});animations.push(a);await a.finished.catch(()=>{});}
const tier=f=>workflow.querySelector('.tier[data-floor="'+f+'"]');
try{await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));await BalVisual.play({animate,stopped:()=>done,text,note});if(!done)commit();}catch{commit();}}

$('startBAL').onclick=()=>start(false);skip.onclick=()=>start(true);
if(window.balRecoveryFailed){api.active=true;copy.textContent='Geçiş kaydı tamamlanamadı. Kayıt alanını kontrol edip yeniden yükle.';skip.disabled=false;skip.textContent='Yeniden yükle';skip.onclick=()=>location.reload();$('settingsDialog').showModal();}
if(LeagueRules.config.bal){document.body.classList.add('bal-stage');document.querySelector('#clubPanel .section-top .eyebrow').textContent='BİZİM KULÜP · AŞAMA 2';$('apFeedback').textContent='+'+RoomSystem.effects().clickAP.toLocaleString('tr-TR')+' AP';document.querySelector('.season-hero>.eyebrow').textContent='BAL · SEZON 01';document.querySelector('#leaguePanel .team-heading .eyebrow').textContent='BÖLGESEL AMATÖR LİG';$('blackboardTitle').textContent='Teknik Ekip';}
})();
