(function(){
'use strict';
const names=['Performans Merkezi','Kulüp Yönetimi','Gelir Merkezi','Teknik Ekip','Ekipman Atölyesi'];
const descriptions=['Antrenman ve beslenme, aynı merkezde.','Kulübünün günlük çalışma merkezi.','Talimatlardan bütçeye.','Maça hazırlığın yeni merkezi.','Gelişime uygun ekipmanlar.'];
const scenes=[
'<path d="M18 112H302V173H18Z" fill="#dba972"/><path d="M30 119H215V164H30Z M122 119V164 M30 141H215" fill="none" stroke="#fff2cd" stroke-width="3"/><path d="M121 104V167M128 106V167M116 109H133" stroke="#587e73" stroke-width="3"/><path d="M223 123H300V139H223" fill="#698e7a"/><path d="M229 139V162M293 139V162" stroke="#466957" stroke-width="5"/><rect x="238" y="108" width="17" height="15" rx="4" fill="#f4d78a"/><circle cx="278" cy="116" r="8" fill="#e28e66"/><path d="M24 85V35H85V85Z" fill="#e4f1df"/><path d="M54 35V85M24 60H85" stroke="#fff5db" stroke-width="4"/><rect x="151" y="42" width="125" height="42" rx="6" fill="#608e7a"/><path d="M163 63H185L193 51L204 75L214 60H260" stroke="#f9dc99" fill="none" stroke-width="3"/>',
'<rect x="25" y="27" width="116" height="67" rx="5" fill="#edf0d7"/><path d="M39 44H125M39 57H107M39 70H119" stroke="#97b7a2" stroke-width="5"/><path d="M49 120H257V138H49Z" fill="#bf8d64"/><path d="M59 138V171M247 138V171" stroke="#7f6950" stroke-width="7"/><rect x="95" y="87" width="65" height="35" rx="4" fill="#4f7775"/><path d="M127 122V131" stroke="#e3c99a" stroke-width="5"/><rect x="181" y="109" width="40" height="13" rx="2" fill="#f9e5b1"/><rect x="181" y="105" width="40" height="5" rx="2" fill="#dc9f7d"/><circle cx="258" cy="49" r="21" fill="#fcf0c9"/><path d="M258 35V49L268 54" stroke="#648c80" fill="none" stroke-width="3"/>',
'<rect x="50" y="57" width="221" height="103" rx="6" fill="#efd7a5"/><path d="M41 48H280L270 77H51Z" fill="#648e7a"/><path d="M75 48L80 77M118 48L120 77M161 48V77M204 48L201 77M247 48L242 77" stroke="#f8e5b8" stroke-width="18"/><rect x="67" y="88" width="184" height="31" rx="3" fill="#4c776b"/><rect x="64" y="126" width="194" height="37" rx="4" fill="#c89364"/><rect x="207" y="108" width="30" height="22" rx="3" fill="#708a86"/><circle cx="99" cy="115" r="10" fill="#f6e6b4"/><path d="M130 104H165V124H130Z" fill="#f4bc75"/><rect x="113" y="17" width="95" height="22" rx="8" fill="#fff2ca"/>',
'<rect x="29" y="24" width="237" height="115" rx="7" fill="#bb9466"/><rect x="36" y="31" width="223" height="99" rx="3" fill="#426c62"/><path d="M61 47H164V114H61ZM112 47V114M61 80H164" fill="none" stroke="#d1ddbb" stroke-width="2"/><g fill="#efc775"><circle cx="80" cy="64" r="5"/><circle cx="135" cy="99" r="5"/><circle cx="144" cy="64" r="5"/></g><path d="M84 64Q120 76 135 93M187 54H241M187 66H229M187 98H238" stroke="#f5d79b" fill="none" stroke-width="3"/><path d="M62 139L52 173M231 139L241 173" stroke="#876d50" stroke-width="7"/><rect x="180" y="111" width="59" height="8" rx="3" fill="#f3e5c8"/>',
'<path d="M33 29H177V159H33Z" fill="#9d795a"/><path d="M40 36H170V70H40ZM40 77H170V111H40ZM40 118H170V152H40Z" fill="#d9b98b"/><g fill="#fff0ca" stroke="#89a99b" stroke-width="2"><circle cx="64" cy="54" r="12"/><circle cx="103" cy="54" r="12"/><circle cx="143" cy="54" r="12"/></g><path d="M57 88H88V106H57ZM106 85H153V106H106Z" fill="#739786"/><path d="M193 122H289V137H193Z" fill="#b98860"/><path d="M204 137V171M280 137V171" stroke="#7f694f" stroke-width="6"/><circle cx="239" cy="106" r="17" fill="#f4d183"/><path d="M226 95L250 117M225 109L246 93" stroke="#fff3d2" stroke-width="3"/><rect x="208" y="37" width="63" height="42" rx="5" fill="#64887d"/><path d="M219 56H260M239 46V68" stroke="#e8d3a8" stroke-width="4"/>'
];
function art(f){return '<svg class="bal-room-art" viewBox="0 0 320 180" aria-hidden="true"><rect width="320" height="180" fill="'+['#bfd9cd','#d6dfcf','#d5dfbd','#b7d0c4','#ded0b3'][f]+'"/><path d="M0 113H320V180H0Z" fill="#d4b68d"/><path d="M0 113H320" stroke="#faf0d0" stroke-width="5"/>'+scenes[f]+'</svg>'}
function decorate(card,f){const room=card.querySelector('.room');room.classList.add('bal-illustrated');room.innerHTML=art(f)+'<span class="room-label" hidden></span>';card.querySelector('h3').textContent=names[f];const purpose=card.querySelector('.department-purpose');if(purpose)purpose.textContent=descriptions[f];}
async function play({animate,stopped,text,note}){
 const workflow=document.getElementById('workflow'),tier=f=>workflow.querySelector('.tier[data-floor="'+f+'"]'),base=f=>tier(f).querySelector('.base-room'),ease='cubic-bezier(.22,1,.36,1)',scrollBox=workflow.closest('.building-scroll');
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const move=(el,frames,duration=700)=>animate(el,frames,{duration,easing:ease});
 async function focus(el){scrollBox.scrollLeft=0;const top=window.scrollY+el.getBoundingClientRect().top-Math.max(110,(innerHeight-180-el.offsetHeight)/2);if(reduced){window.scrollTo({top,behavior:'instant'});return}const start=scrollY,end=Math.max(0,top),begin=performance.now();await new Promise(resolve=>{function frame(now){if(stopped())return resolve();const p=Math.min(1,(now-begin)/480);window.scrollTo({top:start+(end-start)*(1-(1-p)**3),behavior:'instant'});p<1?requestAnimationFrame(frame):resolve()}requestAnimationFrame(frame)});}
 const previewState=BalRules.enter(RoomSystem.snapshot(),1);
 async function gather(f){if(stopped())return;const el=tier(f),b=base(f),slot=document.getElementById('roomSlots'+f);el.classList.add('bal-active-tier');await focus(b);if(stopped())return;
 const cards=[...slot.querySelectorAll('.upgrade-room')],foundation=FoundationBlocks.create(f,()=>false);if(!foundation)return;
 foundation.classList.add('bal-foundation-preview');foundation.inert=true;
 if(cards.length){const first=cards[0],target=first.getBoundingClientRect();el.dataset.blockMerge='joining';
 await Promise.all(cards.map((card,i)=>{const rect=card.getBoundingClientRect();card.style.position='relative';card.style.zIndex=String(cards.length-i+5);return animate(card,[{transform:'translate(0,0)',opacity:1},{transform:'translate('+(target.left-rect.left)+'px,'+(target.top-rect.top-i*4)+'px)',opacity:1}],{duration:1150,delay:reduced?0:i*160,easing:'cubic-bezier(.45,0,.2,1)'});}));if(stopped())return;
 const shell=document.createElement('div');shell.className='bal-foundation-shell';first.before(shell);shell.append(foundation);FoundationBlocks.update(previewState);
 const old=document.createElement('div');old.className='bal-foundation-old';old.append(first.cloneNode(true));shell.append(old);for(const card of cards)card.remove();
 el.dataset.blockMerge='revealing';await Promise.all([move(old,[{transform:'translateY(0)',opacity:1},{transform:'translateY(-100%)',opacity:.2}],850),move(foundation,[{transform:'translateY(100%)'},{transform:'translateY(0)'}],850)]);if(stopped())return;
 shell.replaceWith(foundation);
 }else{slot.prepend(foundation);FoundationBlocks.update(previewState);await move(foundation,[{transform:'translateY(25px)',opacity:0},{transform:'translateY(0)',opacity:1}],650);}
 el.dataset.blockMerge='complete';el.classList.remove('bal-active-tier');
 }
 async function reveal(card,f){if(stopped())return;const old=document.createElement('div'),next=document.createElement('div');old.className='bal-card-face bal-face-old';next.className='bal-card-face bal-face-new';while(card.firstChild)old.append(card.firstChild);next.append(...[...old.children].map(n=>n.cloneNode(true)));decorate(next,f);card.classList.add('bal-card-changing');card.append(old,next);await Promise.all([move(old,[{transform:'translateY(0)',opacity:1},{transform:'translateY(-102%)',opacity:.3}],950),move(next,[{transform:'translateY(102%)'},{transform:'translateY(0)'}],950),move(card,[{boxShadow:'0 4px 0 #8daa9c'},{boxShadow:'0 4px 0 #a6ac77,0 0 0 5px #e3ca8b66',offset:.5},{boxShadow:'0 4px 0 #8daa9c'}],1100)]);if(stopped())return;card.replaceChildren(...next.childNodes);card.classList.remove('bal-card-changing');card.classList.add('bal-card-renewed');}
 text.textContent='Bloklar yerlerine toplanıyor';note.textContent='Kulüp Yönetimi';await gather(1);await reveal(base(1),1);if(stopped())return;
 text.textContent='İki departman, tek merkez';note.textContent='Antrenman + Beslenme';await gather(0);await gather(2);if(stopped())return;
 // Keep the real departments in their vertical lanes throughout the merge.
 const a=base(0),b=base(2);const top=tier(0),bottom=tier(2);await focus(top);if(stopped())return;workflow.dataset.mergePhase='joining';
 const ar=a.getBoundingClientRect(),br=b.getBoundingClientRect(),distance=br.top-ar.top;
 top.style.zIndex=4;bottom.style.zIndex=3;
 await Promise.all([move(a,[{transform:'translateY(0)'},{transform:'translateY(16px)',offset:.35},{transform:'translateY(0)'}],1400),move(b,[{transform:'translateY(0)',opacity:1},{transform:'translateY(-'+(distance-14)+'px)',opacity:1,offset:.8},{transform:'translateY(-'+distance+'px)',opacity:0}],1400)]);
 workflow.dataset.mergePhase='revealing';await reveal(a,0);if(stopped())return;
 const food=bottom.querySelector('.foundation-block');if(food){const before=food.getBoundingClientRect();document.getElementById('roomSlots0').querySelector('.foundation-block').after(food);const after=food.getBoundingClientRect();await move(food,[{transform:'translate('+(before.left-after.left)+'px,'+(before.top-after.top)+'px)'},{transform:'translate(0,0)'}],1000);if(stopped())return;}
 const height=bottom.getBoundingClientRect().height;await move(bottom,[{height:height+'px',marginBottom:'16px',opacity:1},{height:'0px',marginBottom:'0px',opacity:0}],650);bottom.hidden=true;bottom.style.display='none';workflow.dataset.mergePhase='complete';
 text.textContent='Kulübün yeni döneme hazırlanıyor';note.textContent='Teknik Ekip';await gather(3);await reveal(base(3),3);if(stopped())return;
 tier(4).hidden=false;tier(4).style.removeProperty('display');note.textContent='Ekipman Atölyesi';await focus(base(4));await reveal(base(4),4);await gather(4);if(stopped())return;text.textContent='Yeni departman açıldı';note.textContent='Gelir Merkezi';const income=tier(2),incomeCard=base(2);income.getAnimations().forEach(x=>x.cancel());incomeCard.getAnimations().forEach(x=>x.cancel());incomeCard.style.opacity='0';income.hidden=false;income.style.removeProperty('display');decorate(incomeCard,2);await focus(incomeCard);await move(incomeCard,[{transform:'translateY(35px)',opacity:0},{transform:'translateY(0)',opacity:1}],900);text.textContent='BAL için hazırız';note.textContent='Yeni başlangıç · Daha hızlı gelişim';await move(base(4),[{opacity:1},{opacity:1}],900);
}
function capture(workflow){const records=[...workflow.querySelectorAll('.tier')].map(t=>{const card=t.querySelector('.base-room');return {t,card,parent:card.parentElement,html:card.innerHTML,slot:t.querySelector('[id^="roomSlots"]'),children:[...t.querySelector('[id^="roomSlots"]').childNodes],childStyles:[...t.querySelector('[id^="roomSlots"]').childNodes].map(n=>n.getAttribute?.('style')),hidden:t.hidden,style:t.getAttribute('style')}});return ()=>{workflow.querySelectorAll('.bal-merge-dock').forEach(d=>d.remove());for(const r of records){r.slot.replaceChildren(...r.children);r.children.forEach((n,i)=>{n.getAnimations?.().forEach(a=>a.cancel());if(n.setAttribute){r.childStyles[i]===null?n.removeAttribute('style'):n.setAttribute('style',r.childStyles[i])}});delete r.t.dataset.blockMerge;r.parent.prepend(r.card);r.card.innerHTML=r.html;r.card.classList.remove('bal-join-card','bal-card-changing','bal-card-renewed');r.card.removeAttribute('style');r.t.hidden=r.hidden;r.style===null?r.t.removeAttribute('style'):r.t.setAttribute('style',r.style);r.t.classList.remove('bal-active-tier')}}}
window.BalVisual={decorate,play,capture};
})();
