(function(){
const labels={receive:'Manşet',serve:'Servis',spike:'Smaç',block:'Blok',set:'Oyun Kurma ve Pas',mental:'Mental',stamina:'Dayanıklılık'};let previous='';
function show(rows){const signature=JSON.stringify(rows);if(signature===previous)return;previous=signature;const el=document.getElementById('blackboardAdvice'),list=document.createElement('dl');for(const [label,text]of rows){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=text;row.append(dt,dd);list.append(row)}el.replaceChildren(list)}
function refresh(){const lead=RoomSystem.blackboard().leadDays,next=LeagueSeason.progress().next;if(!next){show([['Sezon','Prolog tamamlandı.']]);return}let day=1;try{day=JSON.parse(localStorage.getItem('idle-spiker-main-menu-v1')).day}catch{}const remaining=next.day-day,rival=LeagueRules.teams[next.home===0?next.away:next.home],rows=[['Sıradaki rakip',rival+' · '+(remaining>0?remaining+' gün sonra':'Maç günü')]];
if(!lead){show([...rows,['Analiz kapalı','Kara Tahta’dan Rakip Analizi aç.']]);return}if(remaining>lead){show([...rows,['Rapor tarihi',(next.day-lead)+'. gün']]);return}
const squad=TeamView.snapshot(),key=['receive','serve','spike','set'][next.round-1],roles={receive:['libero','outside'],serve:['opposite','outside'],spike:['outside','opposite'],set:['setter']},lineup=new Set(Object.values(squad.lineup));const p=squad.players.filter(p=>lineup.has(p.id)&&roles[key].includes(p.role)&&!TeamRules.cardQuote(p).blocked).sort((a,b)=>a[key]-b[key])[0];rows.push(['Öncelik',labels[key]],['Neden?',['Güçlü servislerini karşıla.','Servisle savunma düzenini boz.','Güçlü bloğuna karşı hücumu geliştir.','İyi pasla daha etkili hücum kur.'][next.round-1]]);if(p)rows.push(['Önerilen oyuncu',p.name+' '+p.surname],['Geliştirme','Kart seviyesi '+TeamRules.cardLevel(p)+' → '+(TeamRules.cardLevel(p)+1)+' · '+TeamRules.cardQuote(p).cost+' AP']);else rows.push(['Kadro notu','Uygun oyuncu yok ya da özellik sınırda.']);show(rows);
}
refresh();setInterval(refresh,1000);
})();
