(function(){
'use strict';
const $=id=>document.getElementById(id),R=TeamRules,C=CampRules;
let selectedId=null,day=1,lastDay=null;
try{const saved=JSON.parse(localStorage.getItem('idle-spiker-main-menu-v1'));if(Number.isSafeInteger(saved?.day)&&saved.day>0)day=saved.day}catch{}
const portal=document.createElement('dialog');portal.id='campDialog';portal.setAttribute('aria-labelledby','campTitle');portal.innerHTML='<button type="button" id="closeCamp" aria-label="Kampı kapat">×</button><span class="camp-eyebrow">KULÜP ETKİNLİĞİ</span>';document.body.append(portal);portal.append($('campPanel'));$('closeCamp').onclick=()=>portal.close();
const overview=document.createElement('section');overview.className='camp-overview';overview.innerHTML='<div><span>01 · DUYURU</span><b>7 gün hazırlan</b></div><div><span>02 · KAYIT</span><b>Oyuncunu seç</b></div><div><span>03 · KAMP</span><b>7 gün sonra +5 sınır</b></div><p id="campEntryCost"></p>';$('campStatus').after(overview);
let tourSeen=false,tour=null;try{tourSeen=localStorage.getItem('idle-spiker-camp-tour-v1')==='done'}catch{}
function finishTour(){tourSeen=true;try{localStorage.setItem('idle-spiker-camp-tour-v1','done')}catch{}tour?.remove();tour=null;$('campAlert').classList.remove('camp-spotlight');}
function openCamp(){const first=!tourSeen;finishTour();render();if(!portal.open)portal.showModal();if(first){portal.classList.add('camp-guiding');const help=document.createElement('aside');help.className='camp-first-help';help.innerHTML='<strong>Önce takvim ve maliyet</strong><p>Burada kampın tarihini ve oyuncu başına ücretini görürsün. Kayıt açılınca kartını seç; kamp 7 oyun günü sonra stat sınırını +5 artırır.</p><button type="button">Oyuncuları göster</button>';overview.after(help);help.querySelector('button').onclick=()=>{portal.classList.remove('camp-guiding');help.remove();$('campCandidates').scrollIntoView({block:'nearest',behavior:'smooth'})};help.querySelector('button').focus({preventScroll:true});}else $('campEntryCost').focus({preventScroll:true});}
function teach(){if(tourSeen||tour||portal.open||document.hidden||window.MatchGateway?.active()||window.BalTransition?.active||document.querySelector('dialog[open]'))return;const alert=$('campAlert');if(alert.hidden||!alert.getClientRects().length)return;alert.scrollIntoView({behavior:'instant',block:'center'});alert.classList.add('camp-spotlight');tour=document.createElement('div');tour.className='camp-tour';tour.setAttribute('role','dialog');tour.setAttribute('aria-label','Antrenman Kampı tanıtımı');tour.innerHTML='<div class="camp-tour-shade"></div><section><small>YENİ ETKİNLİK</small><h3>Oyuncularına yeni bir gelişim alanı</h3><p>Stat sınırına yaklaşan oyuncular kampa katılabilir. <strong>Antrenman Kampı</strong> kartından takvimi ve gereken AP ile bütçeyi görebilirsin.</p><button type="button">Kampı incele →</button><button class="camp-tour-later" type="button">Daha sonra</button></section>';document.body.append(tour);tour.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();finishTour()}else if(e.key==='Tab'){const buttons=[...tour.querySelectorAll('button')],i=buttons.indexOf(document.activeElement);e.preventDefault();buttons[(i+(e.shiftKey?-1:1)+buttons.length)%buttons.length].focus()}});tour.querySelector('button').onclick=openCamp;tour.querySelector('.camp-tour-later').onclick=finishTour;const r=alert.getBoundingClientRect(),bubble=tour.querySelector('section');bubble.style.top=Math.min(innerHeight-bubble.offsetHeight-20,Math.max(12,r.bottom+12))+'px';tour.querySelector('button').focus({preventScroll:true});}
const fmt=n=>Math.floor(n).toLocaleString('tr-TR');
function state(){return RoomSystem.developmentState()}
function refreshResources(){const s=state(),p=R.players.find(p=>p.id===selectedId);$('campWallet').textContent=fmt(RoomSystem.balance())+' AP · '+fmt(RoomSystem.cashBalance())+' bütçe';const button=$('campEnroll');if(!p){button.disabled=true;button.textContent='Kampa gönder';$('campQuote').textContent='Kampa göndereceğin oyuncuyu seç.';return}const cost=C.price(s,p),free=s.camp.entries.filter(e=>e.status==='running').length<C.config.slots;button.disabled=!C.eligible(s,p)||day<s.camp.opensDay||!free||RoomSystem.balance()<cost.ap||RoomSystem.cashBalance()<cost.cash;button.textContent='Kampa gönder · '+fmt(cost.ap)+' AP + '+fmt(cost.cash)+' bütçe';$('campQuote').textContent=fmt(cost.ap)+' AP + '+fmt(cost.cash)+' bütçe · '+p.name+' '+p.surname+' · Stat sınırı '+R.cap(p)+' → '+(R.cap(p)+C.config.capGain)+' · '+C.config.durationDays+' oyun günü';}
function render(){const s=state(),c=s.camp,visible=s.stage==='bal'&&c.announcedDay!==null;$('campPanel').hidden=!visible;$('campAlert').hidden=!visible;if(!visible)return;day=Math.max(day,c.lastDay);const waiting=day<c.opensDay;
 $('campStatus').textContent=waiting?'Kayıt: '+c.opensDay+'. gün · '+(c.opensDay-day)+' gün kaldı.':'Kayıtlar açık. Kamp 7 oyun günü sürer, oyuncunun stat sınırını 5 artırır.';
 const eligible=R.players.filter(p=>C.eligible(s,p)),costs=eligible.map(p=>C.price(s,p)),minimum=costs.length?{ap:Math.min(...costs.map(x=>x.ap)),cash:Math.min(...costs.map(x=>x.cash))}:{ap:C.config.apCost,cash:C.config.cashCost};$('campAlert').innerHTML='<span class="camp-alert-icon" aria-hidden="true">▱</span><span><strong>Antrenman Kampı</strong><small>'+(waiting?'Kayıtlar '+(c.opensDay-day)+' oyun günü sonra':'Kayıtlar açık · Oyuncunu seç')+'</small><b>'+fmt(minimum.ap)+' AP + '+fmt(minimum.cash)+' bütçeden</b></span><span aria-hidden="true">›</span>';$('campEntryCost').textContent='Oyuncu başına başlangıç bedeli: '+fmt(minimum.ap)+' AP + '+fmt(minimum.cash)+' bütçe. İkinci kampın bedeli iki katıdır.';$('campEntryCost').tabIndex=-1;overview.dataset.waiting=String(waiting);
 $('campSelection').hidden=false;$('campEnroll').title=waiting?'Kayıtlar '+(c.opensDay-day)+' oyun günü sonra açılır.':'';
 const running=c.entries.filter(e=>e.status==='running');$('campSlots').replaceChildren(...Array.from({length:C.config.slots},(_,i)=>{const slot=document.createElement('div'),entry=running[i];slot.className='camp-slot';if(!entry){slot.textContent='Kamp yeri '+(i+1)+' · Boş';return slot}const p=R.players.find(p=>p.id===entry.playerId);const image=document.createElement('img'),name=document.createElement('strong'),timer=document.createElement('span'),progress=document.createElement('progress');image.src=p.art;image.alt=p.name;name.textContent=p.name+' '+p.surname;timer.textContent=(entry.endDay-day)+' gün kaldı · Stat sınırı '+(C.config.balCap+entry.targetBoost);progress.max=C.config.durationDays;progress.value=Math.max(0,C.config.durationDays-(entry.endDay-day));progress.setAttribute('aria-label',p.name+' kamp ilerlemesi');slot.append(image,name,timer,progress);return slot}));
 $('campCandidates').replaceChildren(...R.players.map(p=>{const b=document.createElement('button');b.type='button';b.className='camp-candidate';b.disabled=!C.eligible(s,p);b.setAttribute('aria-pressed',String(p.id===selectedId));const image=document.createElement('img'),name=document.createElement('strong'),cap=document.createElement('small');image.src=p.art;image.alt='';name.textContent=p.name+' '+p.surname;cap.textContent='Stat sınırı '+R.cap(p)+(c.entries.some(e=>e.playerId===p.id&&e.status==='running')?' · Kampta':R.cap(p)>=C.config.balMaxCap?' · En yüksek sınır':!C.near(s,p)?' · En az bir stat '+(R.cap(p)-C.config.nearCap)+' olmalı':' → '+(R.cap(p)+C.config.capGain));b.append(image,name,cap);b.onclick=()=>{selectedId=p.id;render()};return b}));
 if(!R.players.some(p=>p.id===selectedId&&C.eligible(s,p)))selectedId=null;refreshResources();
}
function refresh(){const result=RoomSystem.campSync(R.players,day);if(result.completed.length){$('campNotice').textContent=result.completed.map(id=>{const p=R.players.find(p=>p.id===id);return p.name+' '+p.surname+': stat sınırı '+R.cap(p)}).join(' · ');window.TeamView?.refresh?.()}render()}
$('campEnroll').onclick=()=>{const p=R.players.find(p=>p.id===selectedId);if(!p)return;const ok=RoomSystem.campEnroll(p,day);$('campNotice').textContent=ok?p.name+' '+p.surname+' kampa katıldı. Bitiş: '+(day+C.config.durationDays)+'. oyun günü.':'Kayıt başarısız. AP, bütçe ve kayıt iznini kontrol et.';if(ok)selectedId=null;refresh()};
$('campAlert').onclick=openCamp;setInterval(()=>{if(!tourSeen)teach()},1500);
window.CampSystem={open:openCamp,refresh,refreshResources,advance(next){if(!Number.isSafeInteger(next)||next<1||next===lastDay)return;day=next;lastDay=next;refresh()}};
refresh();
})();
