(function(root){
'use strict';
const config=Object.freeze({prologueCap:50,balCap:100,balMaxCap:110,capGain:5,nearCap:2,noticeDays:7,durationDays:7,slots:3,apCost:1200,cashCost:500});
const defaults=()=>({announcedDay:null,opensDay:null,lastDay:1,boosts:{},entries:[]});
const dayValue=n=>Number.isSafeInteger(n)&&n>=1;
function normalize(raw){const s=defaults();if(!raw||typeof raw!=='object')return s;if(dayValue(raw.lastDay))s.lastDay=raw.lastDay;if(dayValue(raw.announcedDay)){s.announcedDay=raw.announcedDay;s.opensDay=s.announcedDay+config.noticeDays}for(let i=0;i<12;i++){const id='player-'+i,n=raw.boosts?.[id];if(Number.isInteger(n)&&n>=0)s.boosts[id]=Math.min(10,Math.floor(n/5)*5)}const active=new Set();for(const e of Array.isArray(raw.entries)?raw.entries:[]){if(!/^player-(?:[0-9]|1[01])$/.test(e?.playerId)||!dayValue(e.startDay)||![5,10].includes(e.targetBoost))continue;const status=e.status==='complete'?'complete':'running';if(status==='running'&&(active.has(e.playerId)||active.size>=config.slots))continue;if(status==='running')active.add(e.playerId);s.entries.push({playerId:e.playerId,startDay:e.startDay,endDay:e.startDay+config.durationDays,targetBoost:e.targetBoost,status});if(status==='complete')s.boosts[e.playerId]=Math.max(s.boosts[e.playerId]||0,e.targetBoost)}return s}
function cap(s,p){return s?.stage==='bal'?Math.min(config.balMaxCap,config.balCap+(s.camp?.boosts?.[p.id]||0)):config.prologueCap}
function near(s,p){return ['spike','block','serve','receive','set','stamina','mental'].some(k=>Number.isFinite(p[k])&&p[k]>=cap(s,p)-config.nearCap)}
function price(s,p){const tier=1+Math.floor((s.camp.boosts[p.id]||0)/config.capGain);return {ap:config.apCost*tier,cash:config.cashCost*tier}}
function eligible(s,p){return s.stage==='bal'&&!!p&&cap(s,p)<config.balMaxCap&&near(s,p)&&!s.camp.entries.some(e=>e.playerId===p.id&&e.status==='running')}
function update(s,players,day){if(s.stage!=='bal'||!dayValue(day))return {changed:false,announced:false,completed:[]};const c=s.camp;day=Math.max(day,c.lastDay);let changed=day!==c.lastDay;c.lastDay=day;const completed=[];for(const e of c.entries){if(e.status==='running'&&day>=e.endDay){c.boosts[e.playerId]=Math.max(c.boosts[e.playerId]||0,e.targetBoost);e.status='complete';changed=true;completed.push(e.playerId)}}let announced=false;if(c.announcedDay===null&&players.some(p=>eligible(s,p))){c.announcedDay=day;c.opensDay=day+config.noticeDays;announced=true;changed=true}return {changed,announced,completed}}
function enroll(s,p,day){if(!dayValue(day)||!eligible(s,p)||s.camp.opensDay===null||day<s.camp.opensDay||day<s.camp.lastDay||s.camp.entries.filter(e=>e.status==='running').length>=config.slots)return false;const cost=price(s,p);if(!Number.isFinite(s.ap)||!Number.isFinite(s.budget)||s.ap<cost.ap||s.budget<cost.cash)return false;s.ap-=cost.ap;s.budget-=cost.cash;s.camp.entries.push({playerId:p.id,startDay:day,endDay:day+config.durationDays,targetBoost:(s.camp.boosts[p.id]||0)+config.capGain,status:'running'});return true}
const api={config,defaults,normalize,cap,near,price,eligible,update,enroll};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.CampRules=api;
})(globalThis);
