(function(){
'use strict';
const key='idle-spiker-club-profile-v1',colors=['#527d70','#39758c','#a8604c','#725b87','#3d596e','#c39343','#25352f','#e05c4f','#db839d','#8471b3','#2964b5','#238f98','#649247','#b5b856','#ded1ad','#f7f1e1'],accents=['#f6d58b','#fff3df','#bce0d3','#f0bda8','#ffffff','#202e36','#f28c77','#eba9cc','#b9b0ec','#92c5ef','#69cabe','#a3d576'],shapes={shield:'Kalkan',round:'Yuvarlak',pennant:'Flama',hex:'Altıgen',diamond:'Elmas',arch:'Kemer',ticket:'Bilet',crest:'Klasik'},symbols={ball:'Voleybol',bolt:'Şimşek',peak:'Zirve',star:'Yıldız',sun:'Güneş',moon:'Hilal',wave:'Dalga',wing:'Kanat',crown:'Taç',leaf:'Yaprak',flame:'Alev',net:'File'},patterns={plain:'Düz',split:'İki renk',stripe:'Çapraz',bars:'Çubuklar',hoops:'Yatay',chevron:'V şerit',quarters:'Damalı',rays:'Işın'},borders={solid:'Tek çizgi',double:'Çift çizgi',dotted:'Kesik çizgi'};
const defaults={name:'Mahalle Spor',short:'MSK',primary:colors[0],accent:accents[0],shape:'shield',symbol:'ball',pattern:'split',border:'solid'};
function valid(raw){return {name:typeof raw?.name==='string'?raw.name.trim().slice(0,28):defaults.name,short:typeof raw?.short==='string'?raw.short.trim().slice(0,3).toLocaleUpperCase('tr'):defaults.short,primary:/^#[0-9a-f]{6}$/i.test(raw?.primary)?raw.primary.toLowerCase():defaults.primary,accent:/^#[0-9a-f]{6}$/i.test(raw?.accent)?raw.accent.toLowerCase():defaults.accent,shape:Object.hasOwn(shapes,raw?.shape)?raw.shape:defaults.shape,symbol:Object.hasOwn(symbols,raw?.symbol)?raw.symbol:defaults.symbol,pattern:Object.hasOwn(patterns,raw?.pattern)?raw.pattern:defaults.pattern,border:Object.hasOwn(borders,raw?.border)?raw.border:defaults.border}}
let saved=null,draft={...defaults};try{const raw=JSON.parse(localStorage.getItem(key));if(raw)saved=valid(raw)}catch{}
const dialog=document.createElement('dialog');dialog.id='clubJourney';dialog.setAttribute('aria-labelledby','journeyTitle');dialog.innerHTML=`<header class="journey-header"><span>YENİ BİR SAYFA</span><button type="button" id="journeyClose" aria-label="Kapat">×</button></header>
<section id="journeyChoices"><span class="journey-kicker">MAHALLEDEN ÖTESİNE</span><h2 id="journeyTitle">Bu hikâye burada bitmez.</h2><p>Mahalle ligini tamamladın. Yeni ligin için kulübünü tasarla ya da mahallede tam bir sezon oyna.</p><button type="button" class="journey-choice primary" id="journeyNext"><span class="choice-icon">↗</span><span><strong>Sıradaki Lig'e geç</strong><small>Bölgesel Amatör Lig (BAL) · Kulübünü oluştur</small></span><b>›</b></button><button type="button" class="journey-choice" id="journeyReplay"><span class="choice-icon">↻</span><span><strong>Bu ligi en baştan oyna</strong><small>7 maç · Sıfır puanla başlayan tam sezon</small></span><b>›</b></button><p class="journey-note">Oyuncuların, blokların ve kaynakların korunur.</p></section>
<form id="clubCreator" hidden><div class="creator-heading"><span class="journey-kicker">BÖLGESEL AMATÖR LİG · BAL</span><h2>Kulübüne bir kimlik ver.</h2><p>Adın, renklerin, arman. Sahada seni temsil edecek her şey.</p></div><div class="club-preview"><span class="preview-caption">KULÜBÜNÜN ARMASI</span><div id="clubBadge"></div><h3 id="clubNamePreview"></h3><span id="clubShortPreview"></span><div id="clubJersey" aria-hidden="true"></div></div>
<section class="creator-section"><div class="creator-step"><b>01</b><h3>Kulübün adı</h3></div><label>Kulüp adı<input id="clubNameInput" maxlength="28" required autocomplete="organization" placeholder="Kulübünün adı"></label><label>Kısa ad <small>Armanın üzerinde görünür</small><input id="clubShortInput" maxlength="3" required placeholder="MSK"></label></section>
<section class="creator-section"><div class="creator-step"><b>02</b><h3>Renklerin</h3></div><p>Ana renk</p><div id="clubPrimaryColors" class="club-swatches"></div><div class="custom-color"><label class="color-palette"><input id="primaryPicker" type="color" value="#527d70">Paletten seç</label><label class="hex-color">HEX<input id="primaryHex" type="text" maxlength="7" pattern="#[0-9a-fA-F]{6}" aria-label="Ana renk HEX kodu" spellcheck="false"></label></div><p>Vurgu rengi</p><div id="clubAccentColors" class="club-swatches"></div><div class="custom-color"><label class="color-palette"><input id="accentPicker" type="color" value="#f6d58b">Paletten seç</label><label class="hex-color">HEX<input id="accentHex" type="text" maxlength="7" pattern="#[0-9a-fA-F]{6}" aria-label="Vurgu rengi HEX kodu" spellcheck="false"></label></div><button type="button" id="clubSwapColors" class="journey-text">⇄ Renkleri değiştir</button></section>
<section class="creator-section"><div class="creator-step"><b>03</b><h3>Armanı yarat</h3><button type="button" id="clubRandom" class="journey-text">İlham ver</button></div><p>Arma biçimi</p><div id="clubShapes" class="club-options"></div><p>Sembol</p><div id="clubSymbols" class="club-options"></div><p>Desen</p><div id="clubPatterns" class="club-options"></div><p>Çerçeve</p><div id="clubBorders" class="club-options"></div></section>
<div class="creator-actions"><button type="submit" class="creator-save">Kulübümü kaydet <span>→</span></button><button type="button" class="journey-text" id="creatorBack">Seçeneklere dön</button></div></form>
<section id="clubReady" hidden><div id="readyBadge"></div><span class="journey-kicker">KULÜBÜN HAZIR</span><h2 id="readyClubName"></h2><p>Bölgesel Amatör Lig (BAL) için kimliğin hazır. Yeni ligin maçları ve diğer özellikleri daha sonra açılacak.</p><button type="button" class="creator-save" id="editClubIdentity">Kulübü düzenle</button><button type="button" class="journey-text" id="readyBack">Lig seçeneklerine dön</button></section><p id="journeyError" role="alert"></p>`;
document.body.append(dialog);const $=id=>document.getElementById(id);
let emblemId=0;
const outlines={shield:'M20 12H100V65Q100 98 60 113Q20 98 20 65Z',round:'M60 10A50 50 0 1 1 59.99 10Z',pennant:'M22 10H98V87L60 114L22 87Z',hex:'M60 7L105 33V88L60 115L15 88V33Z',diamond:'M60 5L108 60L60 118L12 60Z',arch:'M17 48Q17 8 60 8Q103 8 103 48V108H17Z',ticket:'M20 15H100V42Q83 51 100 60V107H20V60Q37 51 20 42Z',crest:'M60 8Q80 22 103 15V61Q103 92 60 115Q17 92 17 61V15Q40 22 60 8Z'};
const icons={ball:'<circle cx="60" cy="49" r="22"/><path d="M43 35Q64 30 78 64M60 27Q62 53 40 57M82 47Q57 43 52 69"/>',bolt:'<path d="M65 23L42 53H58L53 76L79 43H62Z"/>',peak:'<path d="M34 69L55 29L65 48L73 36L88 69ZM47 45L55 50L61 42"/>',star:'<path d="M60 24L68 41L87 44L73 57L77 76L60 66L43 76L47 57L33 44L52 41Z"/>',sun:'<circle cx="60" cy="50" r="14"/><path d="M60 24V30M60 70V76M34 50H40M80 50H86M41 31L46 36M74 64L79 69M41 69L46 64M74 36L79 31"/>',moon:'<path d="M69 27A24 24 0 1 0 82 63A23 23 0 0 1 69 27Z"/>',wave:'<path d="M34 61Q43 35 61 38Q47 46 54 54Q65 64 86 49Q80 72 59 72Q42 72 34 61ZM39 78H79"/>',wing:'<path d="M34 31L82 43L61 53L45 70L40 56L34 31ZM40 41L68 47M43 52L56 54"/>',crown:'<path d="M37 38L48 48L60 28L72 48L83 38L78 68H42ZM44 76H76"/>',leaf:'<path d="M38 66Q32 30 82 27Q86 72 45 71M38 79L71 38M48 64V49M57 54H72"/>',flame:'<path d="M61 24Q68 36 63 43Q77 40 77 31Q96 62 72 75Q57 83 43 72Q26 57 50 39Q45 56 56 55Q70 48 61 24Z"/>',net:'<path d="M33 29V78M87 29V78M33 36H87V65H33M45 36V65M60 36V65M75 36V65M33 51H87"/>'};
const patternPaths={plain:'',split:'<path d="M60 0H120V124H60Z"/>',stripe:'<path d="M-15 93L120 8V30L0 110Z"/>',bars:'<path d="M25 0V124M60 0V124M95 0V124" fill="none" stroke-width="14"/>',hoops:'<path d="M0 35H120M0 64H120M0 93H120" fill="none" stroke-width="12"/>',chevron:'<path d="M0 26L60 63L120 26V47L60 84L0 47Z"/>',quarters:'<path d="M0 0H60V62H0ZM60 62H120V124H60Z"/>',rays:'<path d="M60 62L0 0H23ZM60 62L89 0H115ZM60 62L120 102V124ZM60 62L0 92V119Z"/>'};
function emblem(profile){const p=profile,outline=outlines[p.shape],svg=document.createElementNS('http://www.w3.org/2000/svg','svg'),id='club-crest-'+(++emblemId);svg.setAttribute('viewBox','0 0 120 124');svg.setAttribute('role','img');svg.setAttribute('aria-label','Kulüp arması');svg.innerHTML='<defs><clipPath id="'+id+'"><path d="'+outline+'"/></clipPath></defs><path d="'+outline+'" fill="'+p.primary+'"/><g clip-path="url(#'+id+')" fill="'+p.accent+'" stroke="'+p.accent+'" opacity=".22">'+patternPaths[p.pattern]+'</g><path d="'+outline+'" fill="none" stroke="'+p.accent+'" stroke-width="'+(p.border==='double'?2:4)+'"'+(p.border==='dotted'?' stroke-dasharray="5 4"':'')+'/>'+(p.border==='double'?'<path d="'+outline+'" fill="none" stroke="'+p.accent+'" stroke-width="2" transform="translate(6 6.2) scale(.9)"/>':'')+'<g fill="none" stroke="'+p.accent+'" stroke-width="3" stroke-linecap="round" stroke-linejoin="round">'+icons[p.symbol]+'</g>';const text=document.createElementNS(svg.namespaceURI,'text');text.setAttribute('x','60');text.setAttribute('y','94');text.setAttribute('text-anchor','middle');text.setAttribute('fill',p.accent);text.setAttribute('font-size','14');text.setAttribute('font-family','Trebuchet MS, sans-serif');text.setAttribute('font-weight','900');text.textContent=p.short||'MSK';svg.append(text);return svg}
function preview(){const p=valid(draft);$('clubBadge').replaceChildren(emblem(p));$('clubNamePreview').textContent=p.name||'Kulübünün adı';$('clubShortPreview').textContent=p.short||'KISA AD';$('clubJersey').innerHTML='<svg viewBox="0 0 90 100"><path d="M27 10L10 18L1 39L17 47L24 32V91H66V32L73 47L89 39L80 18L63 10Q45 23 27 10Z" fill="'+p.primary+'" stroke="'+p.accent+'" stroke-width="3"/><path d="M27 10Q45 38 63 10M27 62H63" fill="none" stroke="'+p.accent+'" stroke-width="5"/></svg>';dialog.style.setProperty('--club-primary',p.primary);for(const prop of ['primary','accent']){if(document.activeElement!==$(prop+'Hex'))$(prop+'Hex').value=p[prop];$(prop+'Picker').value=p[prop]}for(const b of dialog.querySelectorAll('[data-choice]')){b.setAttribute('aria-pressed',String(draft[b.dataset.choice]===b.dataset.value));const previous=b.querySelector('svg');if(previous){const sample=emblem({...p,[b.dataset.choice]:b.dataset.value});sample.removeAttribute('role');sample.setAttribute('aria-hidden','true');previous.replaceWith(sample)}}}
function options(host,prop,values,swatch=false){for(const [value,label]of Object.entries(values)){const b=document.createElement('button');b.type='button';b.dataset.choice=prop;b.dataset.value=value;b.setAttribute('aria-label',label);if(swatch){b.style.setProperty('--swatch',value);b.textContent='✓'}else{const sample=emblem({...defaults,[prop]:value});sample.removeAttribute('role');sample.setAttribute('aria-hidden','true');b.append(sample,document.createTextNode(label));}b.onclick=()=>{draft[prop]=value;preview()};$(host).append(b)}}
options('clubPrimaryColors','primary',Object.fromEntries(colors.map(c=>[c,'Ana renk '+c])),true);options('clubAccentColors','accent',Object.fromEntries(accents.map(c=>[c,'Vurgu rengi '+c])),true);options('clubShapes','shape',shapes);options('clubSymbols','symbol',symbols);options('clubPatterns','pattern',patterns);options('clubBorders','border',borders);
for(const prop of ['primary','accent']){const update=value=>{if(/^#[0-9a-f]{6}$/i.test(value)){draft[prop]=value.toLowerCase();preview()}};$(prop+'Picker').oninput=e=>update(e.target.value);$(prop+'Hex').oninput=e=>update(e.target.value);$(prop+'Hex').onblur=()=>{$(prop+'Hex').value=draft[prop]}};
$('clubSwapColors').onclick=()=>{[draft.primary,draft.accent]=[draft.accent,draft.primary];preview()};

function badgeFeedback(){window.GameAudio?.uiClick();const badge=$('clubBadge');if(!matchMedia('(prefers-reduced-motion: reduce)').matches){badge.getAnimations().forEach(a=>a.cancel());badge.animate([{transform:'scale(.94) rotate(-3deg)'},{transform:'scale(1.06) rotate(2deg)',offset:.55},{transform:'scale(1) rotate(0)'}],{duration:300,easing:'ease-out'})}}
dialog.addEventListener('click',e=>{if(e.target.closest('[data-choice],#clubRandom,#clubSwapColors'))badgeFeedback()});
function view(which){for(const id of ['journeyChoices','clubCreator','clubReady'])$(id).hidden=id!==which;$('journeyError').textContent='';dialog.scrollTop=0;dialog.setAttribute('aria-labelledby',which==='journeyChoices'?'journeyTitle':which==='clubReady'?'readyClubName':'creatorTitle');dialog.querySelector('.creator-heading h2').id='creatorTitle';}
function edit(){draft={...(saved||defaults)};$('clubNameInput').value=draft.name;$('clubShortInput').value=draft.short;view('clubCreator');preview();}
function ready(){view('clubReady');$('readyBadge').replaceChildren(emblem(saved));$('readyClubName').textContent=saved.name;}
function brand(){if(!saved)return;LeagueRules.teams[0]=saved.name;document.querySelectorAll('.current-club-stage').forEach(el=>el.textContent=saved.name);const icon=document.querySelector('.league-quick-icon');if(icon)icon.replaceChildren(emblem(saved));window.LeagueSeason?.refreshView?.();}
$('journeyClose').onclick=()=>dialog.close();$('journeyNext').onclick=()=>saved?ready():edit();$('journeyReplay').onclick=()=>{if(LeagueSeason.replay()){dialog.close();LeagueSeason.open()}else $('journeyError').textContent='Sezon başlatılamadı. Yeniden dene.'};$('creatorBack').onclick=$('readyBack').onclick=()=>view('journeyChoices');$('editClubIdentity').onclick=edit;
$('clubNameInput').oninput=e=>{draft.name=e.target.value;preview()};$('clubShortInput').oninput=e=>{draft.short=e.target.value;preview()};$('clubRandom').onclick=()=>{for(const [prop,values]of Object.entries({primary:colors,accent:accents,shape:Object.keys(shapes),symbol:Object.keys(symbols),pattern:Object.keys(patterns),border:Object.keys(borders)}))draft[prop]=values[Math.floor(Math.random()*values.length)];preview()};
$('clubCreator').onsubmit=e=>{e.preventDefault();const profile=valid(draft);if(profile.name.length<2||!profile.short){$('journeyError').textContent='En az 2 harfli bir kulüp adı ve kısa ad yaz.';return}try{localStorage.setItem(key,JSON.stringify(profile));saved=profile;brand();ready()}catch{$('journeyError').textContent='Kulüp kaydedilemedi. Yeniden dene.'}};
window.ClubJourney={open(){if(!LeagueSeason.progress().prologueComplete)return;view('journeyChoices');if(!dialog.open)dialog.showModal();},profile:()=>saved?{...saved}:null};brand();
})();
