(function(){
'use strict';
const views=new WeakMap(),selected=new Map(),fmt=n=>n.toLocaleString('tr-TR',{maximumFractionDigits:1});
function description(room,n){const v=room.values[Math.max(0,n-1)];switch(room.id){case 'warmup':return 'Her talimata +'+fmt(v*2.5)+' AP';case 'assistant':return fmt(v*2)+' otomatik talimat/sn';case 'offline_time':return v+' saat çevrimdışı AP';case 'steady':return 'Her 10 otomatik talimata +'+fmt(v*1.25)+' AP';case 'echo':return 'Her 5 talimata +'+fmt(v*1.25)+' AP';case 'meal':return 'Gün sonunda +'+fmt(v*1.25)+' AP';case 'energy_drink':return 'İlk 20 talimata +'+fmt(v*1.25)+' AP';case 'sugar_boost':return 'Çevrimdışı AP +%'+fmt(v*1.25*100);case 'crit_smash':return '%'+fmt(v.c*100)+' şansla '+fmt(v.m)+' kat AP';case 'coordinate':return '%'+fmt(v*100)+' şansla ücretsiz yükseltme';case 'collect':return 'Maçtan '+v+' gün önce rakip analizi';case 'rhythm':return 'Mental ve dayanıklılık: %'+fmt(v*100)+' AP indirimi';case 'slots':return 'Manşet ve blok: %'+fmt(v*100)+' AP indirimi';case 'balls':return 'Hücum özellikleri: %'+fmt(v*100)+' AP indirimi';default:return room.describe(v)}}
const completed=new Set(),drawerOpen=new Map();
window.addEventListener('spiker-stage-changed',()=>{completed.clear();drawerOpen.clear()});
function syncDrawers(state){if(state.stage!=='bal'||window.BalTransition?.active)return;
for(const tier of document.querySelectorAll('.bal-tier')){const floor=tier.dataset.floor,base=tier.querySelector('.base-room'),cards=[...tier.querySelectorAll('.foundation-block:not(.bal-foundation-preview)')];let newlyCompleted=false;
for(const card of cards){const rooms=RoomRules.catalog.filter(r=>r.floor===Number(card.dataset.foundation)&&!r.bal),full=rooms.length&&rooms.every(r=>RoomRules.count(state,r.id)>=r.values.length);if(!full)continue;
const fresh=!completed.has(card.dataset.foundation);completed.add(card.dataset.foundation);newlyCompleted=newlyCompleted||fresh&&card.dataset.observed==='true';
if(!card.parentElement.classList.contains('foundation-drawer')){const shell=document.createElement('div');shell.className='foundation-drawer';shell.id='foundation-drawer-'+card.dataset.foundation;card.before(shell);shell.append(card);shell.dataset.open=String(!!drawerOpen.get(floor)||fresh&&card.dataset.observed==='true');}
}
cards.forEach(card=>card.dataset.observed='true');const drawers=[...tier.querySelectorAll('.foundation-drawer')];let button=base.querySelector('.foundation-toggle');
if(!drawers.length){button?.remove();continue}
if(!button){button=document.createElement('button');button.type='button';button.className='foundation-toggle';button.innerHTML='<span>Temeller</span><b aria-hidden="true">›</b>';base.append(button);button.onclick=()=>{const open=button.getAttribute('aria-expanded')!=='true';drawerOpen.set(floor,open);setDrawer(open,true);window.GameAudio?.uiClick?.()};}
button.setAttribute('aria-controls',drawers.map(d=>d.id).join(' '));
function setDrawer(open,focus){button.setAttribute('aria-expanded',String(open));button.setAttribute('aria-label','Tamamlanan temelleri '+(open?'gizle':'göster'));button.title=open?'Temelleri gizle · Etkiler aktif':'Temelleri göster · Etkiler aktif';for(const shell of drawers){if(!open&&shell.contains(document.activeElement))button.focus({preventScroll:true});shell.inert=!open;shell.setAttribute('aria-hidden',String(!open));shell.dataset.open=String(open);}if(open&&focus){const scroll=tier.closest('.building-scroll');const left=base.getBoundingClientRect().left-scroll.getBoundingClientRect().left+scroll.scrollLeft;scroll.scrollTo({left:Math.max(0,left-40),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}}
if(newlyCompleted){drawerOpen.set(floor,false);for(const shell of drawers){shell.dataset.open='true';void shell.offsetWidth;}requestAnimationFrame(()=>{if(button.isConnected)setDrawer(false,false)});}else setDrawer(!!drawerOpen.get(floor),false);
}
}
function update(state){document.querySelectorAll('.foundation-floor').forEach(panel=>{const room=RoomRules.catalog.find(r=>r.id===panel.dataset.id),n=RoomRules.count(state,room.id),max=n>=room.values.length,price=RoomRules.cost(state,room.floor,room.id),lock=RoomRules.requirement(state,room.id),ready=!max&&!lock&&state.budget>=price,signature=[n,price,lock,ready].join('|');if(views.get(panel)===signature)return;views.set(panel,signature);const button=panel.querySelector('.foundation-buy'),tab=document.getElementById('foundation-tab-'+room.id);button.disabled=!ready;panel.dataset.status=max?'max':ready?'ready':'locked';panel.dataset.level=n;tab.dataset.status=panel.dataset.status;tab.setAttribute('aria-label',room.name+' · '+n+'/'+room.values.length+(ready?' · '+(!n?'Açılabilir':'Yükseltilebilir'):''));tab.title=room.name;tab.querySelector('.foundation-tab-pips').innerHTML=room.values.map((_,i)=>'<i class="'+(i<n?'filled':'')+'"></i>').join('');panel.querySelector('.foundation-level').textContent='Seviye '+n+' / '+room.values.length;panel.querySelector('.foundation-effect').textContent=description(room,n);panel.querySelector('.foundation-action').textContent=max?'✓ Tamamlandı':lock||(!n?'＋ Aç':'↑ Yükselt');panel.querySelector('.foundation-price').textContent=max||lock?'':fmt(price)+' bütçe';button.setAttribute('aria-label',room.name+' · '+(max?'Tamamlandı':lock||(!n?'Aç':'Yükselt')+' · '+fmt(price)+' bütçe'));button.title=max?description(room,n):lock||room.describe(room.values[n]);});syncDrawers(state);}
function create(floor,perform){const rooms=RoomRules.catalog.filter(r=>r.floor===floor&&!r.bal);if(!rooms.length)return null;const card=document.createElement('section');card.className='room-tile foundation-block';card.dataset.foundation=floor;card.setAttribute('aria-label',['Antrenman temelleri','Yönetim temelleri','Beslenme temelleri','Teknik temeller','Ekipman temelleri'][floor]);const header=document.createElement('header');header.innerHTML='<span>TEMELLER</span><strong>'+['Antrenman','Yönetim','Beslenme','Teknik','Ekipman'][floor]+'</strong>';const tabs=document.createElement('div');tabs.className='foundation-tabs';tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','Kat seçimi');const body=document.createElement('div');body.className='foundation-body';card.append(header,tabs,body);let active=Math.min(selected.get(floor)||0,rooms.length-1);
function choose(index,focus=false){const previous=active;active=index;selected.set(floor,index);[...tabs.children].forEach((tab,i)=>{tab.setAttribute('aria-selected',String(i===index));tab.tabIndex=i===index?0:-1});[...body.children].forEach((panel,i)=>{panel.getAnimations().forEach(a=>a.cancel());panel.hidden=i!==index});const panel=body.children[index];if(previous!==index&&!matchMedia('(prefers-reduced-motion: reduce)').matches)panel.animate([{transform:'translateX('+(index>previous?18:-18)+'px)',opacity:.2},{transform:'translateX(0)',opacity:1}],{duration:220,easing:'cubic-bezier(.2,.8,.2,1)'});if(focus)tabs.children[index].focus({preventScroll:true});}
for(const [i,room]of rooms.entries()){const tab=document.createElement('button');tab.type='button';tab.className='foundation-tab';tab.id='foundation-tab-'+room.id;tab.setAttribute('role','tab');tab.setAttribute('aria-controls','foundation-panel-'+room.id);tab.innerHTML='<span class="foundation-tab-icon" aria-hidden="true">'+room.icon+'</span><span class="foundation-tab-pips" aria-hidden="true"></span>';tab.onclick=()=>choose(i);tab.onkeydown=e=>{let next=null;if(e.key==='ArrowRight')next=(i+1)%rooms.length;if(e.key==='ArrowLeft')next=(i+rooms.length-1)%rooms.length;if(e.key==='Home')next=0;if(e.key==='End')next=rooms.length-1;if(next!==null){e.preventDefault();choose(next,true)}};const panel=document.createElement('section');panel.className='foundation-floor';panel.dataset.id=room.id;panel.id='foundation-panel-'+room.id;panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby',tab.id);panel.innerHTML='<strong class="foundation-name"></strong><span class="foundation-level"></span><span class="foundation-effect"></span><button type="button" class="foundation-buy"><span class="foundation-action"></span><span class="foundation-price"></span></button>';panel.querySelector('.foundation-name').textContent=room.name;const button=panel.querySelector('button');button.onclick=()=>{if(!perform(room))return;window.GameAudio?.uiClick?.();if(!matchMedia('(prefers-reduced-motion: reduce)').matches)button.animate([{transform:'translateY(2px) scale(.97)'},{transform:'translateY(0) scale(1)'}],{duration:220,easing:'ease-out'});};tabs.append(tab);body.append(panel)}choose(active);return card;}
window.FoundationBlocks={create,update};
})();
