(function(root){
'use strict';
const teams=['Bizim Kulüp','Mavişehir','Çınar Spor','Yıldız Gençlik','Sahil Spor','Kent Akademi','Güneş Spor','Kuzey Voleybol'],start=Date.UTC(2026,8,28),dayMs=86400000;
const config=Object.freeze({name:'Mahalle Kadınlar Ligi',rounds:14,lastDay:98,winPoints:3,lossPoints:0});
const dateFor=day=>new Date(start+(day-1)*dayMs),dayFor=date=>Math.round((Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate())-start)/dayMs)+1;
function fixtures(day){if(!Number.isInteger(day)||day<7||day>config.lastDay||day%7!==0)return[];const week=day/7-1;let ring=teams.map((_,i)=>i);for(let r=0;r<week%7;r++)ring=[ring[0],ring[7],...ring.slice(1,7)];return Array.from({length:4},(_,i)=>{let home=ring[i],away=ring[7-i];if(((week%7)%2===1)!==(week>=7))[home,away]=[away,home];return{id:'r'+(week+1)+'-'+home+'-'+away,day,home,away,time:(13+i*2)+':00',round:week+1,season:1,ours:home===0||away===0}})}
const schedule=()=>Array.from({length:config.rounds},(_,i)=>fixtures((i+1)*7)).flat();
function validScore(score){return Array.isArray(score)&&score.length===2&&score.every(n=>Number.isSafeInteger(n)&&n>=0&&n<=10000)&&score[0]!==score[1]}
function normalize(raw){const results={};for(const m of schedule()){const score=raw?.results?.[m.id];if(validScore(score))results[m.id]=[...score]}return {version:1,results,completionSeen:raw?.completionSeen===true,completedDay:Number.isSafeInteger(raw?.completedDay)&&raw.completedDay>=config.lastDay?raw.completedDay:null}}
function importOwn(state,legacy){let changed=false;for(const m of schedule().filter(m=>m.ours)){if(state.results[m.id]||!validScore(legacy?.[m.day]))continue;state.results[m.id]=m.home===0?[...legacy[m.day]]:[...legacy[m.day]].reverse();changed=true}return changed}
function standings(state){const rows=teams.map((name,id)=>({id,name,played:0,wins:0,losses:0,for:0,against:0,points:0,rank:null}));for(const m of schedule()){const score=state.results[m.id];if(!validScore(score))continue;const h=rows[m.home],a=rows[m.away];h.played++;a.played++;h.for+=score[0];h.against+=score[1];a.for+=score[1];a.against+=score[0];const winner=score[0]>score[1]?h:a,loser=winner===h?a:h;winner.wins++;winner.points+=config.winPoints;loser.losses++;loser.points+=config.lossPoints}for(const r of rows)r.difference=r.for-r.against;rows.sort((a,b)=>b.points-a.points||b.wins-a.wins||b.difference-a.difference||b.for-a.for||a.id-b.id);const any=rows.some(r=>r.played);rows.forEach((r,i)=>{const previous=rows[i-1];r.rank=!any?null:previous&&['points','wins','difference','for'].every(k=>previous[k]===r[k])?previous.rank:i+1});return rows}
function progress(state){const all=schedule(),ours=all.filter(m=>m.ours),played=ours.filter(m=>validScore(state.results[m.id])).length,reported=all.filter(m=>validScore(state.results[m.id])).length;return {played,total:config.rounds,reported,fixtures:all.length,prologueComplete:played===config.rounds,standingsFinal:reported===all.length,next:ours.find(m=>!validScore(state.results[m.id]))||null}}
// Temporary league-only opponent results. Replace this adapter when match balance is finalized.
function temporaryScore(m){let n=2166136261;for(const c of m.id)n=Math.imul(n^c.charCodeAt(0),16777619)>>>0;n^=n<<13;n^=n>>>17;n^=n<<5;const loser=15+((n>>>1)%9);return n&1?[25,loser]:[loser,25]}
function settleRounds(state){let changed=false;for(let round=1;round<=config.rounds;round++){const matches=fixtures(round*7),own=matches.find(m=>m.ours);if(!validScore(state.results[own.id]))continue;for(const m of matches){if(m.ours||validScore(state.results[m.id]))continue;state.results[m.id]=temporaryScore(m);changed=true}}return changed}
function complete(state,day){const done=progress(state).prologueComplete;if(done&&state.completedDay===null){state.completedDay=Math.max(config.lastDay,Number.isSafeInteger(day)?day:config.lastDay);return true}if(!done&&state.completedDay!==null){state.completedDay=null;return true}return false}
function record(state,id,score){if(!schedule().some(m=>m.id===id)||!validScore(score))return false;if(state.results[id])return state.results[id][0]===score[0]&&state.results[id][1]===score[1];state.results[id]=[...score];return true}
const api={teams,config,dateFor,dayFor,fixtures,schedule,validScore,normalize,importOwn,settleRounds,standings,progress,complete,record};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.LeagueRules=api;
})(globalThis);
