(function(){
'use strict';const R=LeagueRules,$=id=>document.getElementById(id),KEY='idle-spiker-league-v1',OWN='idle-spiker-match-results';
let state=R.normalize(null),day=1,clicksToday=0,round=1,tab='standings';
function readMenu(){try{const s=JSON.parse(localStorage.getItem('idle-spiker-main-menu-v1'));if(Number.isSafeInteger(s?.day)&&s.day>0){day=s.day;clicksToday=Number.isInteger(s.clicksToday)?s.clicksToday:0}}catch{}}
readMenu();try{state=R.normalize(JSON.parse(localStorage.getItem(KEY)))}catch{}
function save(next){try{localStorage.setItem(KEY,JSON.stringify(next));state=next;$('leagueSaveNotice').textContent='';return true}catch{$('leagueSaveNotice').textContent='Sonuç kaydedilemedi. Tarayıcının kayıt iznini kontrol et.';return false}}
function reconcile(){const next=R.normalize(state);let changed=false;try{changed=R.importOwn(next,JSON.parse(localStorage.getItem(OWN)))}catch{}changed=R.settleRounds(next)||changed;changed=R.complete(next,day)||changed;if(changed)save(next)}
function selectedScore(m){return state.results[m.id]||null}
function dueFixture(s={day,clicksToday}){const next=R.progress(state).next;return next&&(next.day<s.day||next.day===s.day&&s.clicksToday>=(R.config.matchTrigger||50))?next:null}
function openLeague(){window.LeagueCalendar?.show?.();switchTab('standings');render()}
function resultCard(m,compact=false){const el=document.createElement('article'),score=selectedScore(m);el.className='season-fixture'+(m.ours?' ours':'');const meta=document.createElement('div');meta.className='season-fixture-meta';meta.textContent=m.round+'. maç · '+(m.ours?(m.home===0?'İç saha':'Deplasman'):m.time);const sides=document.createElement('div');sides.className='season-fixture-teams';const home=document.createElement('strong'),middle=document.createElement('b'),away=document.createElement('strong');home.textContent=R.teams[m.home];away.textContent=R.teams[m.away];middle.textContent=score?score.join(' – '):'VS';sides.append(home,middle,away);const status=document.createElement('small');if(score){const won=m.ours&&(m.home===0?score[0]>score[1]:score[1]>score[0]);status.textContent=m.ours?(won?'GALİBİYET':'MAĞLUBİYET'):'Tamamlandı';status.className=m.ours?(won?'won':'lost'):''}else status.textContent=m.ours?(m.day<day?'Oynanmayı bekliyor':m.day===day?'Bugün · '+(R.config.matchTrigger||50)+'. talimatta':'Oyun günü '+m.day):'Hafta sonuçları bekleniyor';el.append(meta,sides,status);if(m.ours&&!score&&dueFixture()?.id===m.id){const b=document.createElement('button');b.type='button';b.className='fixture-play';b.textContent='Maça git';b.onclick=()=>window.MatchGateway?.play?.(m.day);el.append(b)}return el}
function render(){document.querySelector('.season-hero h2').textContent=R.config.bal?'Bölgesel Amatör Lig':(R.config.replay||R.config.bal)?'Mahallede yeni sezon':'Mahallenin son umudu';document.querySelector('.season-facts span:nth-child(2)').textContent=((R.config.replay||R.config.bal)?'Tam sezon · ':'Son ')+R.config.rounds+' maç';const progress=R.progress(state),rows=R.standings(state),own=rows.find(r=>r.id===0),next=progress.next;const rank=own.rank===null?'—':own.rank+'.';$('leagueQuickTitle').textContent=progress.prologueComplete?(R.config.bal?'BAL sezonu tamamlandı':'Prolog tamamlandı'):R.config.name;$('leagueQuickRecord').textContent=progress.played+' / '+R.config.rounds;$('leagueQuickNext').textContent=next?rank+' sıra · '+own.points+' puan · Sıradaki: '+R.teams[next.home===0?next.away:next.home]:rank+' sıra · '+own.wins+' galibiyet · '+own.points+' puan';$('leagueNavStatus').textContent=progress.prologueComplete?'✓':progress.played+'/'+R.config.rounds;$('seasonPlace').textContent=rank;$('seasonPoints').textContent=own.points;$('seasonWins').textContent=own.wins+' galibiyet · '+own.losses+' mağlubiyet';$('seasonPlayed').textContent=progress.played+' / '+R.config.rounds+' maç';$('seasonProgress').max=R.config.rounds;$('seasonProgress').value=progress.played;$('seasonStatus').textContent=progress.prologueComplete?'Sezon tamamlandı · '+rank+' sırada bitirdin.':next?next.round+'. maç · '+R.teams[next.home===0?next.away:next.home]+' · '+(next.home===0?'İç saha':'Deplasman'):'';$('prologueComplete').hidden=!progress.prologueComplete;$('leagueJourneyButton').hidden=R.config.bal||!progress.prologueComplete;$('standingsState').textContent=progress.standingsFinal?'SEZON SONU':progress.reported?'GÜNCEL TABLO':'DEVRALDIĞIN TABLO';$('standingsPending').textContent=progress.standingsFinal?'Tüm maçlar tamamlandı.':((R.config.replay||R.config.bal)?'Yeni sezon · ':'Devraldığında: 3 mağlubiyet. Son ')+R.config.rounds+' tur: '+progress.reported+' / '+progress.fixtures+' maç tamamlandı.';
 $('standingsRows').replaceChildren(...rows.map(r=>{const tr=document.createElement('tr');if(r.id===0)tr.className='our-standing';for(const value of [r.rank===null?'—':r.rank,r.name,r.played,r.wins,r.losses,r.points]){const td=document.createElement('td');td.textContent=value;tr.append(td)}return tr}));$('roundLabel').textContent=round+'. MAÇ / '+R.config.rounds;$('roundDate').textContent=R.dateFor(R.config.matchDays[round-1]).toLocaleDateString('tr-TR',{day:'numeric',month:'long',timeZone:'UTC'});$('previousRound').disabled=round===1;$('nextRound').disabled=round===R.config.rounds;$('roundFixtures').replaceChildren(...R.fixtures(R.config.matchDays[round-1]).map(m=>resultCard(m)));$('seasonRoute').replaceChildren(...R.schedule().filter(m=>m.ours).map(m=>resultCard(m,true)));$('endRankValue').textContent=rank;$('endWinValue').textContent=own.wins;$('endPointsValue').textContent=own.points;const outcome=R.config.bal?'BAL sezonunu '+rank+' sırada tamamladın.':R.config.replay?'Mahalle ligini '+rank+' sırada tamamladın.':progress.rescued?'Takımı 8. sıradan '+rank+' sıraya taşıdın. Mahalle liginde ilk 4 hedefini başardın!':'Son '+R.config.rounds+' maç tamamlandı. Takım '+rank+' sırada; ilk 4 hedefi bu kez gerçekleşmedi.';$('seasonEndText').textContent=outcome;$('prologueOutcome').textContent=outcome;$('prologueComplete').querySelector('strong').textContent=R.config.bal?'BAL sezonu tamamlandı!':'Prolog tamamlandı!';$('seasonEndTitle').textContent=R.config.bal?'BAL sezonu tamamlandı':progress.rescued?'Mahallede yeniden umut!':'Prolog tamamlandı';}
function switchTab(next){tab=next;for(const name of ['standings','fixtures','dates']){$(name+'Pane').hidden=name!==tab;$(name+'Tab').setAttribute('aria-selected',String(name===tab));$(name+'Tab').tabIndex=name===tab?0:-1}$('calendarNow').hidden=tab!=='dates';if(tab==='dates')window.LeagueCalendar?.refreshView?.()}
for(const name of ['standings','fixtures','dates']){$(name+'Tab').onclick=()=>switchTab(name);$(name+'Tab').onkeydown=e=>{const names=['standings','fixtures','dates'];let target=null;if(e.key==='ArrowRight')target=names[(names.indexOf(name)+1)%3];if(e.key==='ArrowLeft')target=names[(names.indexOf(name)+2)%3];if(e.key==='Home')target=names[0];if(e.key==='End')target=names[2];if(target){e.preventDefault();switchTab(target);$(target+'Tab').focus()}}}
$('previousRound').onclick=()=>{round=Math.max(1,round-1);render()};$('nextRound').onclick=()=>{round=Math.min(R.config.rounds,round+1);render()};$('leagueQuick').onclick=openLeague;$('leagueJourneyButton').onclick=()=>window.ClubJourney?.open();
function showCompletion(){if(!R.progress(state).prologueComplete||state.completionSeen||$('seasonEndDialog').open||window.MatchGateway?.active?.())return;render();$('seasonEndDialog').showModal()}
$('inspectSeason').onclick=()=>{$('seasonEndDialog').close();openLeague()};$('closeSeasonEnd').onclick=()=>$('seasonEndDialog').close();$('seasonEndDialog').addEventListener('close',()=>{save({...state,completionSeen:true})});
function syncRewards(){if(!window.RoomSystem)return true;for(const m of R.schedule().filter(m=>m.ours)){const score=state.results[m.id];if(score&&R.config.bal&&!window.RoomSystem.claimAttendance(m.id))return false;if(score&&(m.home===0?score[0]>score[1]:score[1]>score[0])&&!window.RoomSystem.claimMatchReward(m.id,m.round))return false}return true}
function record(id,score){const next=R.normalize(state);if(!R.record(next,id,score))return false;R.settleRounds(next);R.complete(next,day);if(!save(next))return false;if(!syncRewards()){$('leagueSaveNotice').textContent='Galibiyet ödülü kaydedilemedi. Yeniden dene.';return false}round=R.progress(state).next?.round||R.config.rounds;render();window.LeagueCalendar?.refreshView?.();window.MenuUI?.refresh?.();return true}
window.LeagueSeason={loadStage(raw){state=R.normalize(raw);readMenu();round=1;switchTab("standings");render();},open:openLeague,replay(){if(R.config.bal)return false;if(!R.progress(state).prologueComplete)return false;const previous=state;const next=R.normalize({mode:'replay',run:(state.run||0)+1,startDay:day,results:{}});if(!save(next)){R.configure(previous);return false}round=1;render();window.LeagueCalendar?.refreshView?.();window.MenuUI?.refresh?.();return true;},syncRewards,refresh(s){const changed=day!==s.day,matchReadinessChanged=(clicksToday>=(R.config.matchTrigger||50))!==(s.clicksToday>=(R.config.matchTrigger||50));day=s.day;clicksToday=s.clicksToday;if(changed)round=R.progress(state).next?.round||R.config.rounds;if(changed||matchReadinessChanged&&!$('leaguePanel').hidden)render()},refreshView:render,dueFixture,score:selectedScore,progress:()=>R.progress(state),recordResult:record,recordOwn(matchDay,score){const m=R.fixtures(matchDay).find(m=>m.ours);return !!m&&R.validScore(score)&&record(m.id,m.home===0?score:[...score].reverse())},showCompletion};
window.addEventListener('storage',e=>{if(e.key===KEY||e.key===OWN){try{if(e.key===KEY)state=R.normalize(JSON.parse(e.newValue));readMenu();reconcile();render()}catch{}}});
reconcile();round=R.progress(state).next?.round||R.config.rounds;switchTab('standings');render();setTimeout(showCompletion,0);
})();
