(function(root){
'use strict';
const teams=['Bizim Kulüp','Mavişehir','Çınar Spor','Yıldız Gençlik','Sahil Spor','Kent Akademi','Güneş Spor','Kuzey Voleybol'],start=Date.UTC(2026,8,28),dayMs=86400000;
const config={name:'Mahalle Kadınlar Ligi',rounds:5,lastDay:24,matchDays:[4,9,14,19,24],startingRank:8,targetRank:4,winPoints:3,lossPoints:0};
let replay=null,bal=null;
function configure(raw){bal=raw?.mode==='bal'&&Number.isSafeInteger(raw.startDay)&&raw.startDay>0?{run:1,startDay:raw.startDay}:null;replay=raw?.mode==='replay'&&Number.isSafeInteger(raw.run)&&raw.run>0&&Number.isSafeInteger(raw.startDay)&&raw.startDay>0?{run:raw.run,startDay:raw.startDay}:null;const days=bal?Array.from({length:14},(_,i)=>bal.startDay+(i===0?4:i===1?9:15+(i-2)*8)):replay?Array.from({length:7},(_,i)=>replay.startDay+3+i*5):[4,9,14,19,24];config.matchDays.splice(0,config.matchDays.length,...days);config.rounds=days.length;config.lastDay=days.at(-1);config.replay=!!replay;config.bal=!!bal;config.name=bal?'Bölgesel Amatör Lig (BAL)':'Mahalle Kadınlar Ligi';config.dayInstructions=bal?500:100;config.matchTrigger=bal?300:50;}
const dateFor=day=>new Date(start+(day-1)*dayMs),dayFor=date=>Math.round((Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate())-start)/dayMs)+1;
function pairings(week,day,round,prefix='rescue'){let ring=teams.map((_,i)=>i);for(let r=0;r<week;r++)ring=[ring[0],ring[7],...ring.slice(1,7)];return Array.from({length:4},(_,i)=>{let home=ring[i],away=ring[7-i];if(week%2)[home,away]=[away,home];return {id:prefix+round+'-'+home+'-'+away,day,home,away,time:(13+i*2)+':00',round,season:1,ours:home===0||away===0}})}
function fixtures(day){const index=config.matchDays.indexOf(day);return index<0?[]:pairings(index%7,day,index+1,bal?'bal1_r':replay?'replay'+replay.run+'_r':'rescue').map(m=>{if(bal&&index>=7){[m.home,m.away]=[m.away,m.home];m.id='bal1_r'+m.round+'-'+m.home+'-'+m.away}return m})}
const schedule=()=>config.matchDays.flatMap(fixtures);
const history=()=>replay||bal?[]:[4,5,6].flatMap((w,i)=>pairings(w,0,i+1,'history'));
function historicalScore(m){if(m.ours)return m.home===0?[23,25]:[25,23];const winner=m.home;return winner===m.home?[25,20]:[20,25]}
function validScore(score){return Array.isArray(score)&&score.length===2&&score.every(n=>Number.isSafeInteger(n)&&n>=0&&n<=10000)&&score[0]!==score[1]}
function normalize(raw){configure(raw);const results={};for(const m of schedule()){let score=raw?.results?.[m.id];if(raw?.version===1&&!score)score=raw?.results?.['r'+m.round+'-'+m.home+'-'+m.away];if(validScore(score))results[m.id]=[...score]}return {version:3,...(bal?{mode:'bal',...bal}:replay?{mode:'replay',...replay}:{}),results,legacyResults:raw?.legacyResults||(raw?.version===1?raw.results:{}),completionSeen:raw?.completionSeen===true&&schedule().filter(m=>m.ours).every(m=>validScore(results[m.id])),completedDay:Number.isSafeInteger(raw?.completedDay)&&raw.completedDay>=config.lastDay?raw.completedDay:null}}
function importOwn(state,legacy){if((replay||bal)&&legacy?.version!==3)return false;let changed=false;for(const m of schedule().filter(m=>m.ours)){const oldDays=Object.keys(legacy||{}).some(k=>['3','6','9','12'].includes(k));const score=legacy?.version===3?legacy?.[m.id]:legacy?.[oldDays?[3,6,9,12][m.round-1]:m.round*7];if(state.results[m.id]||!validScore(score))continue;state.results[m.id]=m.home===0?[...score]:[...score].reverse();changed=true}return changed}
function standings(state){const rows=teams.map((name,id)=>({id,name,played:0,wins:0,losses:0,for:0,against:0,points:0,rank:null}));for(const m of [...history(),...schedule()]){const score=m.day===0?historicalScore(m):state.results[m.id];if(!validScore(score))continue;const h=rows[m.home],a=rows[m.away];h.played++;a.played++;h.for+=score[0];h.against+=score[1];a.for+=score[1];a.against+=score[0];const winner=score[0]>score[1]?h:a,loser=winner===h?a:h;winner.wins++;winner.points+=config.winPoints;loser.losses++;loser.points+=config.lossPoints}for(const r of rows)r.difference=r.for-r.against;rows.sort((a,b)=>b.points-a.points||b.wins-a.wins||b.difference-a.difference||b.for-a.for||a.id-b.id);const any=rows.some(r=>r.played);rows.forEach((r,i)=>{const previous=rows[i-1];r.rank=!any?null:previous&&['points','wins','difference','for'].every(k=>previous[k]===r[k])?previous.rank:i+1});return rows}
function progress(state){const all=schedule(),ours=all.filter(m=>m.ours),played=ours.filter(m=>validScore(state.results[m.id])).length,reported=all.filter(m=>validScore(state.results[m.id])).length,rank=standings(state).find(r=>r.id===0).rank;return {rank,rescued:rank!==null&&rank<=config.targetRank,climbed:rank===null?0:config.startingRank-rank,played,total:config.rounds,reported,fixtures:all.length,prologueComplete:played===config.rounds,standingsFinal:reported===all.length,next:ours.find(m=>!validScore(state.results[m.id]))||null}}
// Off-screen fixtures use the same contact probabilities as the court engine.
function temporaryScore(m){const M=typeof module!=='undefined'&&module.exports?require('./match-rules.js'):root.MatchRules,T=typeof module!=='undefined'&&module.exports?require('./team-rules.js'):root.TeamRules;const roster=id=>Array.from({length:6},(_,i)=>{const p=T.opponentStats(bal?m.round:Math.max(1,8-id),i,bal?'bal':'prologue');if(!bal&&id<=3)for(const k of ['spike','serve','receive','set','block'])p[k]+=12+(3-id)*3;return p});return M.simulateSet([roster(m.home),roster(m.away)],m.id)}
function settleRounds(state){let changed=false;for(let round=1;round<=config.rounds;round++){const matches=fixtures(config.matchDays[round-1]),own=matches.find(m=>m.ours);if(!validScore(state.results[own.id]))continue;for(const m of matches){if(m.ours||validScore(state.results[m.id]))continue;state.results[m.id]=temporaryScore(m);changed=true}}return changed}
function complete(state,day){const done=progress(state).prologueComplete;if(done&&state.completedDay===null){state.completedDay=Math.max(config.lastDay,Number.isSafeInteger(day)?day:config.lastDay);return true}if(!done&&state.completedDay!==null){state.completedDay=null;return true}return false}
function record(state,id,score){if(!schedule().some(m=>m.id===id)||!validScore(score))return false;if(state.results[id])return state.results[id][0]===score[0]&&state.results[id][1]===score[1];state.results[id]=[...score];return true}
try{if(root.localStorage){configure(JSON.parse(root.localStorage.getItem('idle-spiker-league-v1')));const profile=JSON.parse(root.localStorage.getItem('idle-spiker-club-profile-v1'));if(typeof profile?.name==='string'&&profile.name.trim())teams[0]=profile.name.trim().slice(0,28)}}catch{}
const api={teams,config,configure,dateFor,dayFor,fixtures,schedule,history,historicalScore,validScore,normalize,importOwn,settleRounds,standings,progress,complete,record};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.LeagueRules=api;
})(globalThis);
