(function(root){
'use strict';
const teams=['Bizim Kulüp','Mavişehir','Çınar Spor','Yıldız Gençlik','Sahil Spor','Kent Akademi','Güneş Spor','Kuzey Voleybol'],start=Date.UTC(2026,8,28),dayMs=86400000;
const config=Object.freeze({name:'Mahalle Kadınlar Ligi',rounds:4,lastDay:12,matchDays:[3,6,9,12],startingRank:8,targetRank:4,winPoints:3,lossPoints:0});
const dateFor=day=>new Date(start+(day-1)*dayMs),dayFor=date=>Math.round((Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate())-start)/dayMs)+1;
function pairings(week,day,round,prefix='rescue'){let ring=teams.map((_,i)=>i);for(let r=0;r<week;r++)ring=[ring[0],ring[7],...ring.slice(1,7)];return Array.from({length:4},(_,i)=>{let home=ring[i],away=ring[7-i];if(week%2)[home,away]=[away,home];return {id:prefix+round+'-'+home+'-'+away,day,home,away,time:(13+i*2)+':00',round,season:1,ours:home===0||away===0}})}
function fixtures(day){const index=config.matchDays.indexOf(day);return index<0?[]:pairings(index,day,index+1)}
const schedule=()=>config.matchDays.flatMap(fixtures);
const history=()=>[4,5,6].flatMap((w,i)=>pairings(w,0,i+1,'history'));
function historicalScore(m){if(m.ours)return m.home===0?[23,25]:[25,23];const winner=m.home;return winner===m.home?[25,20]:[20,25]}
function validScore(score){return Array.isArray(score)&&score.length===2&&score.every(n=>Number.isSafeInteger(n)&&n>=0&&n<=10000)&&score[0]!==score[1]}
function normalize(raw){const results={};for(const m of schedule()){let score=raw?.results?.[m.id];if(raw?.version!==2&&!score)score=raw?.results?.['r'+m.round+'-'+m.home+'-'+m.away];if(validScore(score))results[m.id]=[...score]}return {version:2,results,legacyResults:raw?.legacyResults||(raw?.version===1?raw.results:{}),completionSeen:raw?.completionSeen===true,completedDay:Number.isSafeInteger(raw?.completedDay)&&raw.completedDay>=config.lastDay?raw.completedDay:null}}
function importOwn(state,legacy){let changed=false;for(const m of schedule().filter(m=>m.ours)){const score=legacy?.[m.day]||legacy?.[m.round*7];if(state.results[m.id]||!validScore(score))continue;state.results[m.id]=m.home===0?[...score]:[...score].reverse();changed=true}return changed}
function standings(state){const rows=teams.map((name,id)=>({id,name,played:0,wins:0,losses:0,for:0,against:0,points:0,rank:null}));for(const m of [...history(),...schedule()]){const score=m.day===0?historicalScore(m):state.results[m.id];if(!validScore(score))continue;const h=rows[m.home],a=rows[m.away];h.played++;a.played++;h.for+=score[0];h.against+=score[1];a.for+=score[1];a.against+=score[0];const winner=score[0]>score[1]?h:a,loser=winner===h?a:h;winner.wins++;winner.points+=config.winPoints;loser.losses++;loser.points+=config.lossPoints}for(const r of rows)r.difference=r.for-r.against;rows.sort((a,b)=>b.points-a.points||b.wins-a.wins||b.difference-a.difference||b.for-a.for||a.id-b.id);const any=rows.some(r=>r.played);rows.forEach((r,i)=>{const previous=rows[i-1];r.rank=!any?null:previous&&['points','wins','difference','for'].every(k=>previous[k]===r[k])?previous.rank:i+1});return rows}
function progress(state){const all=schedule(),ours=all.filter(m=>m.ours),played=ours.filter(m=>validScore(state.results[m.id])).length,reported=all.filter(m=>validScore(state.results[m.id])).length,rank=standings(state).find(r=>r.id===0).rank;return {rank,rescued:rank<=config.targetRank,climbed:config.startingRank-rank,played,total:config.rounds,reported,fixtures:all.length,prologueComplete:played===config.rounds,standingsFinal:reported===all.length,next:ours.find(m=>!validScore(state.results[m.id]))||null}}
// Temporary league-only opponent results. Replace this adapter when match balance is finalized.
function temporaryScore(m){let n=2166136261;for(const c of m.id)n=Math.imul(n^c.charCodeAt(0),16777619)>>>0;n^=n<<13;n^=n>>>17;n^=n<<5;const loser=15+((n>>>1)%9);return m.home<m.away?[25,loser]:[loser,25]}
function settleRounds(state){let changed=false;for(let round=1;round<=config.rounds;round++){const matches=fixtures(config.matchDays[round-1]),own=matches.find(m=>m.ours);if(!validScore(state.results[own.id]))continue;for(const m of matches){if(m.ours||validScore(state.results[m.id]))continue;state.results[m.id]=temporaryScore(m);changed=true}}return changed}
function complete(state,day){const done=progress(state).prologueComplete;if(done&&state.completedDay===null){state.completedDay=Math.max(config.lastDay,Number.isSafeInteger(day)?day:config.lastDay);return true}if(!done&&state.completedDay!==null){state.completedDay=null;return true}return false}
function record(state,id,score){if(!schedule().some(m=>m.id===id)||!validScore(score))return false;if(state.results[id])return state.results[id][0]===score[0]&&state.results[id][1]===score[1];state.results[id]=[...score];return true}
const api={teams,config,dateFor,dayFor,fixtures,schedule,history,historicalScore,validScore,normalize,importOwn,settleRounds,standings,progress,complete,record};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.LeagueRules=api;
})(globalThis);
