(function(){
'use strict';
const roles={middle:'Orta oyuncu',outside:'Smaçör',setter:'Pasör',opposite:'Pasör çaprazı',libero:'Libero'},cache=new Map();let timer=null,done=null,current=0,elapsed=0,last=0,teams=[];
const host=document.createElement('section');host.id='matchIntro';host.hidden=true;host.setAttribute('aria-label','Takım tanıtımı');host.innerHTML='<header><span class="eyebrow">SAHNE SİZİN</span><h2>Oyuncular sahaya çıkıyor</h2><div class="intro-versus"></div></header><div class="intro-tabs"><button type="button" data-side="0">Bizim takım</button><button type="button" data-side="1">Rakip takım</button></div><div class="intro-team" aria-live="polite"><h3></h3><p></p></div><div class="intro-cards"></div><div class="intro-libero"></div><footer><div class="intro-progress"><i></i></div><button type="button" class="team-action" id="introNext">Rakibi tanı →</button><button type="button" class="team-secondary" id="introSkip">Tanıtımı geç</button></footer>';
document.getElementById('gameMatchDialog').append(host);
function opponents(f){const team=f.home===0?f.away:f.home;if(!cache.has(team)){const rng=MatchRules.seeded('opponent-appearance-'+team),names=['Duru','Defne','Nehir','Zeynep','İrem','Ada','Yağmur','Eylül','Ceren','İdil','Ece','Selin'],surnames=['Kaya','Yıldız','Aydın','Demir','Aksoy','Çelik','Arslan','Güneş'];cache.set(team,Array.from({length:6},(_,i)=>{const appearance=TeamAppearance.generate(rng);appearance.palette.shirt='#698faa';for(const p of appearance.parts)if(p.path.includes('/Shirts/'))p.tint=appearance.palette.shirt;return {id:'opponent-'+team+'-'+i,name:names[(team*3+i)%names.length],surname:surnames[(team+i*3)%surnames.length],number:i+1,appearance}}))}return cache.get(team).map((p,i)=>({...p,...TeamRules.opponentStats(f.round,i)}))}
function card(p,index,libero=false){const el=document.createElement('article');el.className='intro-card'+(libero?' libero-card':'');el.style.setProperty('--card-index',index);const badge=document.createElement('span');badge.className='intro-number';badge.textContent='#'+p.number;const img=document.createElement('img');img.src=TeamAppearance.portrait(p.appearance);img.alt=p.name+' '+p.surname;const copy=document.createElement('div'),name=document.createElement('strong'),role=document.createElement('small');name.textContent=p.name+' '+p.surname;role.textContent=roles[p.role];copy.append(name,role);el.append(badge,img,copy);return el}
function show(side){current=side;elapsed=0;last=performance.now();host.dataset.side=side;host.querySelector('.intro-team h3').textContent=teams[side].name;host.querySelector('.intro-team p').textContent=side?'Karşındaki altılı':'Seçtiğin ilk altılı';host.querySelectorAll('[data-side]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.side)===side)));host.querySelector('.intro-cards').replaceChildren(...teams[side].players.filter(p=>p.role!=='libero').map((p,i)=>card(p,i)));const libero=teams[side].players.find(p=>p.role==='libero');host.querySelector('.intro-libero').replaceChildren(...(libero?[card(libero,6,true)]:[]));document.getElementById('introNext').textContent=side?'Sahaya çık →':'Rakibi tanı →';host.querySelector('.intro-progress i').style.width='0%';host.scrollTop=0;}
function finish(){if(!done)return;clearInterval(timer);timer=null;host.hidden=true;const callback=done;done=null;callback()}
function advance(){if(current===0)show(1);else finish()}
window.MatchIntro={opponents,show(squad,f,callback){clearInterval(timer);done=callback;const rival=f.home===0?f.away:f.home;teams=[{name:LeagueRules.teams[0],players:['p','s1','s2','pc','o1','o2','l'].map(k=>squad.players.find(p=>p.id===squad.lineup[k]))},{name:LeagueRules.teams[rival],players:squad.opponents}];host.querySelector('.intro-versus').textContent=teams[0].name+'  /  '+teams[1].name;host.hidden=false;show(0);document.getElementById('introNext').focus({preventScroll:true});timer=setInterval(()=>{const now=performance.now(),dt=now-last;last=now;if(document.hidden)return;elapsed+=dt;host.querySelector('.intro-progress i').style.width=Math.min(100,elapsed/52)+'%';if(elapsed>=5200)advance()},100)},cancel(){clearInterval(timer);timer=null;done=null;host.hidden=true}};
host.querySelectorAll('[data-side]').forEach(b=>b.onclick=()=>show(Number(b.dataset.side)));document.getElementById('introNext').onclick=advance;document.getElementById('introSkip').onclick=finish;
})();
