(function(){
const dialog=document.getElementById('gameMatchDialog'),frame=document.getElementById('gameMatchFrame'),button=document.getElementById('exitGameMatch'),prompt=document.getElementById('matchWatchPrompt');let finished=false,skipRequested=false,loading=false,matchDay=null;
function current(){try{return JSON.parse(localStorage.getItem('idle-spiker-main-menu-v1'))||{day:1,clicksToday:0}}catch{return {day:1,clicksToday:0}}}
function openMatch(day){if(dialog.open)return;finished=false;loading=false;matchDay=day;button.hidden=true;frame.hidden=true;prompt.hidden=false;prompt.querySelector('p').textContent=LeagueRules.fixtures(day).find(m=>m.ours)?.round+'. hafta · Takımın sahaya çıkmaya hazır.';document.getElementById('watchMatch').textContent='Evet, maçı izle';document.getElementById('watchMatch').onclick=()=>start(false);dialog.showModal();document.getElementById('watchMatch').focus()}
window.MatchGateway={active:()=>dialog.open,check(state){const fixture=window.LeagueSeason?.dueFixture(state);if(fixture)openMatch(fixture.day)},play(day){const fixture=window.LeagueSeason?.dueFixture(current());if(fixture?.day===day)openMatch(day)}};
function skip(){button.disabled=true;button.textContent='Sonuç hesaplanıyor…';frame.contentWindow.postMessage({type:'spiker-match',action:'skip'},'*')}
function start(skipping){if(loading)return;const squad=window.TeamView?.snapshot();if(!squad||Object.values(squad.lineup).some(id=>!id)){prompt.querySelector('p').textContent='Maça çıkmak için 6 oyuncu ve libero slotlarını doldur.';document.getElementById('watchMatch').textContent='Kadroyu tamamla';document.getElementById('watchMatch').onclick=()=>{dialog.close();document.getElementById('teamTab').click()};return}loading=true;skipRequested=skipping;prompt.hidden=true;frame.hidden=false;button.hidden=false;button.disabled=true;button.onclick=skip;button.textContent=skipping?'Sonuç hesaplanıyor…':'Maç hazırlanıyor…';window.GameAudio?.setMode('match');frame.src='mac.html'}
window.MatchGateway.resumeIfReady=()=>{if(!window.TeamView?.snapshot()||Object.values(window.TeamView.snapshot().lineup).some(id=>!id))return;window.MatchGateway.check(current())};
document.getElementById('watchMatch').onclick=()=>start(false);document.getElementById('skipMatch').onclick=()=>start(true);button.onclick=skip;
function persistResult(score){if(!window.LeagueSeason?.recordOwn(matchDay,score)){button.hidden=false;button.disabled=false;button.textContent='Sonucu kaydetmeyi yeniden dene';button.onclick=()=>persistResult(score);return}finished=true;button.hidden=true;try{const results=JSON.parse(localStorage.getItem('idle-spiker-match-results')||'{}');results[matchDay]=score;localStorage.setItem('idle-spiker-match-results',JSON.stringify(results))}catch{}}
window.addEventListener('message',e=>{if(e.source!==frame.contentWindow||e.data?.type!=='spiker-match'||!dialog.open)return;if(e.data.action==='ready'&&loading){frame.contentWindow.postMessage({type:'spiker-match',action:'squad',squad:{...window.TeamView.snapshot(),matchInfo:(()=>{const f=LeagueRules.fixtures(matchDay).find(m=>m.ours);return {names:[LeagueRules.teams[0],LeagueRules.teams[f.home===0?f.away:f.home]],round:f.round,league:LeagueRules.config.name}})(),opponents:Array.from({length:6},(_,i)=>TeamRules.opponentStats(Math.ceil(matchDay/7),i))}},'*')}if(e.data.action==='squad-ready'&&loading){if(skipRequested)skip();else{button.disabled=false;button.textContent='Maçı atla'}}if(e.data.action==='finished'&&loading&&!finished&&LeagueRules.validScore(e.data.score))persistResult(e.data.score);if(e.data.action==='return'&&finished)dialog.close()});
dialog.addEventListener('cancel',e=>{if(!finished)e.preventDefault()});dialog.addEventListener('close',()=>{frame.src='about:blank';window.GameAudio?.setMode('menu');document.getElementById('energyButton').focus();window.LeagueSeason?.showCompletion?.()});
})();
