(function(){
let squad=null,identitySprites={},applied=false;const oldDraw=draw,oldReset=reset,oldTick=tick;
if(parent!==window)paused=true;
function visibleIdentity(p){if(!squad||p.team!==0)return null;const key=['o1','s1','p','o2','s2','pc'][p.index],base=squad.players.find(q=>q.id===squad.lineup[key]);const back=[1,5,6].includes(p.zone),serving=servingTeam===0&&p.zone===1;return base?.role==='middle'&&back&&!serving?squad.players.find(q=>q.id===squad.lineup.l):base}
function sync(){if(!applied)return;for(const p of players){const identity=p.team===1?squad.opponents?.[p.index%6]:visibleIdentity(p);if(!identity)continue;if(p.team===1){const fatigue=1-Math.min(.22,Math.max(0,elapsed-120)/1800*(1-identity.stamina/100)),pressure=1-Math.min(.12,Math.max(0,scores[0]-scores[1])*.012*(1-identity.mental/100));p.stats={...identity};for(const k of ['spike','block','serve','receive','set'])p.stats[k]=identity[k]*fatigue*pressure;continue;}p.roster=identity;p.displayName=identity.name+' '+identity.surname;p.jerseyNumber=identity.number;const fatigue=1-Math.min(.22,Math.max(0,elapsed-120)/1800*(1-identity.stamina/100)),pressure=1-Math.min(.12,Math.max(0,scores[1]-scores[0])*.012*(1-identity.mental/100));p.stats={...identity};for(const k of ['spike','block','serve','receive','set'])p.stats[k]=identity[k]*fatigue*pressure;if(identitySprites[identity.id])sprites[p.index]=identitySprites[identity.id]}}
draw=function(){sync();oldDraw()};tick=function(dt){sync();oldTick(dt)};reset=function(){oldReset();sync()};
async function apply(data){if(!data?.players||!data?.lineup)return;const keys=['p','s1','s2','pc','o1','o2','l'];if(keys.some(k=>!data.players.some(p=>p.id===data.lineup[k])))return;squad=data;paused=true;while(!ready)await new Promise(r=>setTimeout(r,30));for(const id of new Set(Object.values(data.lineup))){const identity=data.players.find(p=>p.id===id),palette=identity.appearance?.palette;if(!palette)continue;const result={};for(const part of LAYOUT){const c=document.createElement('canvas');c.width=part.width;c.height=part.height;const x=c.getContext('2d');x.drawImage(await load(ASSETS[part.path]),0,0);x.globalCompositeOperation='source-in';x.fillStyle=shade(identity.role==='libero'&&part.colorSource==='shirt'?'#edc457':palette[part.colorSource],part.shade??1);x.fillRect(0,0,c.width,c.height);result[part.id]=c}identitySprites[id]=result}applied=true;sync();paused=false;parent.postMessage({type:'spiker-match',action:'squad-ready'},'*')}
window.addEventListener('message',e=>{if(e.source===parent&&e.data?.type==='spiker-match'&&e.data.action==='squad')apply(e.data.squad).catch(()=>{announce('Kadro yüklenemedi. Sayfayı yenileyip tekrar dene.')})});
})();
