(function(){
const space=document.querySelector('.court-space'),courtBox=document.querySelector('.court-viewport');function fitCourt(){const w=Math.max(0,Math.min(space.clientWidth,space.clientHeight*620/1000));courtBox.style.width=w+'px';courtBox.style.height=(w*1000/620)+'px'}new ResizeObserver(fitCourt).observe(space);fitCourt();
const baseAward=awardPoint,baseSound=matchSound;let finished=false,skipping=false,fast=false;
const totals=Array.from({length:2},()=>({spike:0,block:0,ace:0,error:0})),scorers=new Map();let lastPoint=0;
function tally(winner){const events=history.slice(lastPoint),event=events.filter(e=>e.type==='resolution'&&e.winner).at(-1);let kind='error',index=null;if(event){if(event.event==='kill'&&event.team===winner){kind='spike';index=event.player}else if(event.event==='ace'&&event.team===winner){kind='ace';index=event.player}else if(event.event==='block'&&event.team!==winner){kind='block';index=event.blockers?.[0]}}totals[winner][kind]++;const p=players.find(p=>p.index===index&&p.team===winner);if(p){const name=p.displayName||p.roster?.name||'#'+(p.index%6+1),key=winner+':'+(p.roster?.id||name);if(!scorers.has(key))scorers.set(key,{name,team:winner,points:0});scorers.get(key).points++}}
function resultStats(){const host=document.createElement('section');host.id='resultStats';const heading=document.createElement('h3');heading.textContent='Sayı dağılımı';host.append(heading);const legend=document.createElement('div');legend.className='result-stat-row result-stat-legend';for(const text of [teamName(0),'',teamName(1)]){const span=document.createElement('span');span.textContent=text;legend.append(span)}host.append(legend);for(const [key,label]of [['spike','Smaç'],['block','Blok'],['ace','Servis sayısı'],['error','Rakip hatası']]){const row=document.createElement('div');row.className='result-stat-row';for(const text of [totals[0][key],label,totals[1][key]]){const span=document.createElement('span');span.textContent=text;row.append(span)}host.append(row)}const title=document.createElement('h3');title.textContent='En çok sayı alanlar';host.append(title);const list=document.createElement('ol');list.className='result-scorers';for(const [i,p]of [...scorers.values()].sort((a,b)=>b.points-a.points||a.name.localeCompare(b.name,'tr')).slice(0,3).entries()){const row=document.createElement('li'),rank=document.createElement('i'),copy=document.createElement('span'),name=document.createElement('strong'),team=document.createElement('small'),points=document.createElement('b');rank.textContent=i+1;name.textContent=p.name;team.textContent=teamName(p.team);points.textContent=p.points+' sayı';copy.append(name,team);row.append(rank,copy,points);list.append(row)}if(!list.children.length){const empty=document.createElement('li');empty.textContent='Sayılar rakip hatalarından geldi.';list.append(empty)}host.append(list);document.getElementById('resultScore').after(host)}
const notify=(action,data={})=>parent.postMessage({type:'spiker-match',action,...data},'*');
matchSound=function(...args){if(!skipping)baseSound(...args)};
awardPoint=function(winner){if(finished)return;const finalScore=[...scores];finalScore[winner]++;tally(winner);baseAward(winner);lastPoint=history.length;if(sets[0]+sets[1]>0){finished=true;skipping=false;paused=true;scores=finalScore;updateScore();document.getElementById('matchSet').textContent='MAÇ SONU';document.getElementById('serveTeam').textContent='MAÇ TAMAMLANDI';announce(teamName(winner)+' maçı kazandı!');baseSound('finish');document.getElementById('resultTitle').textContent=sets[0]>0?'Kazandık!':'Bu kez rakip kazandı';document.getElementById('resultScore').textContent=teamName(0)+' '+finalScore[0]+' – '+finalScore[1]+' '+teamName(1);resultStats();document.getElementById('matchResult').hidden=false;document.getElementById('mobilePause').disabled=true;document.getElementById('mobileSpeed').disabled=true;notify('finished',{score:finalScore})}};
function skipChunk(){if(finished)return;if(!ready){setTimeout(skipChunk,100);return}paused=false;for(let i=0;i<1800&&!finished;i++)tick(1/60);paused=true;if(!finished)setTimeout(skipChunk,0)}
window.addEventListener('message',e=>{if(e.source!==parent||e.data?.type!=='spiker-match'||e.data.action!=='skip'||skipping||finished)return;skipping=true;paused=true;document.getElementById('event').textContent='Maçın kalan kısmı oynanıyor…';document.getElementById('mobilePause').disabled=true;document.getElementById('mobileSpeed').disabled=true;skipChunk()});
window.addEventListener('message',e=>{if(e.source===parent&&e.data?.type==='spiker-match'&&e.data.action==='reward'){let p=document.getElementById('matchReward');if(!p){p=document.createElement('section');p.id='matchReward';document.getElementById('resultContinue').before(p)}p.replaceChildren();const title=document.createElement('h3');title.textContent='Maç ödülleri';p.append(title);const amounts=e.data.rewards;if(amounts){const grid=document.createElement('div');grid.className='result-rewards';for(const [value,label]of [['+'+amounts.ap+' AP','Antrenman Puanı'],['+'+amounts.dailyBudget+' / gün','Günlük bütçe artışı']]){const cell=document.createElement('div'),b=document.createElement('b'),small=document.createElement('small');b.textContent=value;small.textContent=label;cell.append(b,small);grid.append(cell)}p.append(grid)}else{const text=document.createElement('p');text.textContent=e.data.text;p.append(text)}}});
document.getElementById('resultContinue').onclick=()=>notify('return');
document.getElementById('mobilePause').onclick=()=>{if(finished||skipping)return;document.getElementById('pause').click();document.getElementById('mobilePause').textContent=paused?'▶ Devam et':'Ⅱ Duraklat'};
document.getElementById('mobileSpeed').onclick=()=>{fast=!fast;document.getElementById('speed').value=fast?'1.5':'1';document.getElementById('mobileSpeed').textContent=fast?'Hız · 1.5×':'Hız · 1×'};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&!paused&&!skipping)document.getElementById('mobilePause').click()});notify('ready');
})();
