(function(){
const dialog=document.getElementById('gameMatchDialog'),frame=document.getElementById('gameMatchFrame'),button=document.getElementById('exitGameMatch'),prompt=document.getElementById('matchWatchPrompt');let finished=false,skipRequested=false,loading=false,matchDay=null,matchSquad=null;
function current(){try{return JSON.parse(localStorage.getItem('idle-spiker-main-menu-v1'))||{day:1,clicksToday:0}}catch{return {day:1,clicksToday:0}}}
function openMatch(day){if(dialog.open)return;finished=false;loading=false;matchDay=day;button.hidden=true;frame.hidden=true;prompt.hidden=false;prompt.querySelector('p').textContent=LeagueRules.fixtures(day).find(m=>m.ours)?.round+'. maç / 4 · '+['Güçlü servis, zayıf manşet.','Dirençli savunma, uzun ralliler.','Güçlü blok, açık arka alan.','Dengeli kadro: son sınav.'][LeagueRules.fixtures(day).find(m=>m.ours).round-1]+' Galibiyet: AP ve günlük bütçe +2.';document.getElementById('watchMatch').textContent='Kadroyu onayla · Maçı izle';document.getElementById('watchMatch').onclick=()=>start(false);window.PreMatch.open(LeagueRules.fixtures(day).find(m=>m.ours));dialog.showModal();prompt.tabIndex=-1;prompt.focus({preventScroll:true});prompt.scrollTop=0}
window.MatchGateway={active:()=>dialog.open,check(state){const fixture=window.LeagueSeason?.dueFixture(state);if(fixture)openMatch(fixture.day)},play(day){const fixture=window.LeagueSeason?.dueFixture(current());if(fixture?.day===day)openMatch(day)}};
function skip(){button.disabled=true;button.textContent='Sonuç hesaplanıyor…';frame.contentWindow.postMessage({type:'spiker-match',action:'skip'},'*')}
function start(skipping){if(loading)return;if(!window.PreMatch.commit())return;const squad=window.TeamView?.snapshot();if(!squad||Object.values(squad.lineup).some(id=>!id)){prompt.querySelector('p').textContent='Maça çıkmak için 6 oyuncu ve libero slotlarını doldur.';document.getElementById('watchMatch').textContent='Kadroyu tamamla';document.getElementById('watchMatch').onclick=editTeam;return}loading=true;skipRequested=skipping;prompt.hidden=true;const f=LeagueRules.fixtures(matchDay).find(m=>m.ours);matchSquad={...squad,matchInfo:{fixtureId:f.id,names:[LeagueRules.teams[0],LeagueRules.teams[f.home===0?f.away:f.home]],round:f.round,league:LeagueRules.config.name},opponents:MatchIntro.opponents(f)};MatchIntro.show(matchSquad,f,()=>{frame.hidden=false;button.hidden=false;button.disabled=true;button.onclick=skip;button.textContent=skipping?'Sonuç hesaplanıyor…':'Maç hazırlanıyor…';window.GameAudio?.setMode('match');frame.src='mac.html'})}
window.MatchGateway.resumeIfReady=()=>{if(!window.TeamView?.snapshot()||Object.values(window.TeamView.snapshot().lineup).some(id=>!id))return;window.MatchGateway.check(current())};
function editTeam(){window.PreMatch.editFirst();}
document.getElementById('editMatchTeam').onclick=editTeam;
document.getElementById('watchMatch').onclick=()=>start(false);document.getElementById('skipMatch').onclick=()=>start(true);button.onclick=skip;
function persistResult(score){if(!window.LeagueSeason?.recordOwn(matchDay,score)){button.hidden=false;button.disabled=false;button.textContent='Sonucu kaydetmeyi yeniden dene';button.onclick=()=>persistResult(score);return}finished=true;button.hidden=true;const round=LeagueRules.fixtures(matchDay).find(m=>m.ours).round;frame.contentWindow.postMessage({type:'spiker-match',action:'reward',text:score[0]>score[1]?'Galibiyet: +'+(250+150*round)+' AP · Günlük bütçe +2 → '+window.RoomSystem.dailyBudget():'Takımını geliştir, sıradaki maça hazırlan.'},'*');try{const results=JSON.parse(localStorage.getItem('idle-spiker-match-results')||'{}');results.version=3;results[LeagueRules.fixtures(matchDay).find(m=>m.ours).id]=score;localStorage.setItem('idle-spiker-match-results',JSON.stringify(results))}catch{}}
window.addEventListener('message',e=>{if(e.source!==frame.contentWindow||e.data?.type!=='spiker-match'||!dialog.open)return;if(e.data.action==='ready'&&loading){frame.contentWindow.postMessage({type:'spiker-match',action:'squad',squad:matchSquad},'*')}if(e.data.action==='squad-ready'&&loading){if(skipRequested)skip();else{button.disabled=false;button.textContent='Maçı atla'}}if(e.data.action==='finished'&&loading&&!finished&&LeagueRules.validScore(e.data.score))persistResult(e.data.score);if(e.data.action==='return'&&finished)dialog.close()});
dialog.addEventListener('cancel',e=>{if(!finished)e.preventDefault()});dialog.addEventListener('close',()=>{window.MatchIntro.cancel();frame.src='about:blank';window.GameAudio?.setMode('menu');document.getElementById('energyButton').focus();window.LeagueSeason?.showCompletion?.()});
})();
