(function(){
'use strict';const host=document.querySelector('.court-space'),layer=document.createElement('div');layer.className='match-bubbles';layer.setAttribute('aria-label','Baloncuk patlatma');host.append(layer);const reduced=matchMedia('(prefers-reduced-motion: reduce)');const bubbles=new Set(),fx=new Set();let untilWave=4,last=0,frame,stopped=false,lastPop=0,chain=0;
const rand=(a,b)=>a+Math.random()*(b-a);
function effect(node,lifetime){layer.append(node);fx.add(node);setTimeout(()=>{node.remove();fx.delete(node)},lifetime)}
function pop(b){if(!bubbles.has(b)||paused||document.hidden||stopped)return;bubbles.delete(b);const x=b.node.offsetLeft+24,y=b.node.offsetTop+24;b.node.remove();const now=performance.now();chain=now-lastPop<1600?chain+1:1;lastPop=now;const ring=document.createElement('span');ring.className='bubble-ring';ring.style.left=x+'px';ring.style.top=y+'px';ring.style.setProperty('--bubble-color',b.color);effect(ring,480);if(!reduced.matches)for(let i=0;i<7;i++){const spark=document.createElement('i'),angle=i/7*Math.PI*2;spark.className='bubble-droplet';spark.style.left=x+'px';spark.style.top=y+'px';spark.style.background=b.color;spark.style.setProperty('--dx',Math.cos(angle)*rand(23,43)+'px');spark.style.setProperty('--dy',Math.sin(angle)*rand(23,43)+'px');effect(spark,550)}const word=document.createElement('span');word.className='bubble-pop-label';word.textContent=chain>1?'POP! ×'+chain:'POP!';word.style.left=Math.max(40,Math.min(host.clientWidth-40,x))+'px';word.style.top=Math.max(26,y-14)+'px';effect(word,700)}
function spawn(){if(bubbles.size>=4||host.clientWidth<80||host.clientHeight<100)return;const node=document.createElement('button'),color=['#a9ece4','#ffd99c','#ddb9ed','#acd9f7'][Math.floor(rand(0,4))];node.type='button';node.className='match-bubble';const icons=[{name:'Voleybol topu',svg:'<circle cx="16" cy="16" r="11"/><path d="M7 9c8-1 13 5 14 16M16 5c-1 7-5 12-11 14M27 14c-7-2-13 3-16 12"/>'},{name:'File',svg:'<path d="M4 7v21M28 7v21M5 10h22v13H5M10 10v13M16 10v13M22 10v13M5 16h22"/>'},{name:'Smaç',svg:'<circle cx="23" cy="9" r="5"/><path d="M9 5l6 3M5 10l9 3M4 16l9 2M23 17l-9 10M14 21v6h6"/>'}];const icon=icons[Math.floor(Math.random()*icons.length)];node.setAttribute('aria-label',icon.name+' baloncuğunu patlat');node.style.setProperty('--bubble-color',color);node.innerHTML='<span class="bubble-shine"></span><svg class="bubble-volley-icon" viewBox="0 0 32 32" aria-hidden="true">'+icon.svg+'</svg>';const b={node,color,age:0,life:rand(5,7),side:Math.random()<.5?0:1,y:rand(.28,.82),phase:rand(0,6)};node.onclick=()=>pop(b);bubbles.add(b);layer.append(node)}
function clear(){for(const b of bubbles)b.node.remove();bubbles.clear();for(const n of fx)n.remove();fx.clear()}
function update(now){const dt=Math.min(.05,last?(now-last)/1000:0);last=now;const active=typeof ready!=='undefined'&&ready&&!paused&&!document.hidden&&!stopped;
// Use the result panel as the final stop, even if another control changes pause.
const running=active&&document.getElementById('matchResult').hidden;
layer.hidden=!running;if(running){untilWave-=dt;if(untilWave<=0){for(let i=0;i<Math.floor(rand(2,4));i++)spawn();untilWave=rand(9,14)}for(const b of bubbles){b.age+=dt;if(b.age>b.life){b.node.remove();bubbles.delete(b);continue}const w=host.clientWidth,h=host.clientHeight;const x=b.side? w-58:10;const drift=reduced.matches?0:Math.sin(b.phase+b.age*1.8)*5;const y=Math.max(5,Math.min(h-53,b.y*h-(reduced.matches?0:b.age*9)));b.node.style.left=(x+drift)+'px';b.node.style.top=y+'px';b.node.style.opacity=String(Math.min(1,b.age*4,(b.life-b.age)*2));b.node.style.transform=reduced.matches?'none':'scale('+(1+Math.sin(b.age*2+b.phase)*.035)+')'}}frame=requestAnimationFrame(update)}
window.addEventListener('message',e=>{if(e.source===parent&&e.data?.type==='spiker-match'&&e.data.action==='skip'){stopped=true;clear()}});window.addEventListener('pagehide',()=>{cancelAnimationFrame(frame);clear()});frame=requestAnimationFrame(update);
})();
