(function(){
'use strict';
let draft={},fixture=null,selected=null;const $=id=>document.getElementById(id),short={middle:'ORTA',outside:'SMAÇÖR',setter:'PASÖR',opposite:'ÇAPRAZ',libero:'LİBERO'};
const jersey='<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M15 5 5 11 1 22l10 4 3-6v23h20V20l3 6 10-4-4-11-10-6c-2 6-16 6-18 0Z" fill="currentColor"/></svg>';
function token(p,slot,away,index){const el=document.createElement(away?'div':'button');el.className='formation-player'+(away?' rival':'');if(!away){el.type='button';el.dataset.slot=slot;el.onclick=()=>choose(slot);el.setAttribute('aria-label',(p?p.name+' '+p.surname:'Boş slot')+' · '+TeamRules.slots.find(s=>s.id===slot).name+' · Oyuncuyu değiştir')}el.style.setProperty('--entry',index);const shirt=document.createElement('span');shirt.className='formation-shirt';shirt.innerHTML=jersey;const number=document.createElement('b');number.textContent=p?.number||index+1;shirt.append(number);const name=document.createElement('strong');name.textContent=p?p.name+' '+p.surname:'Oyuncu seç';const role=document.createElement('small');role.textContent=away?short[p.role]:p?short[p.role]:TeamRules.slots.find(s=>s.id===slot).name;el.append(shirt,name,role);return el}
function render(animate=false){const stage=$('preMatchStage'),squad=TeamView.snapshot(),rival=fixture.home===0?fixture.away:fixture.home;stage.replaceChildren();stage.className=animate?'formation-intro':'';const awayName=document.createElement('h3');awayName.textContent=LeagueRules.teams[rival];const court=document.createElement('div');court.className='formation-court';court.setAttribute('aria-label','İki takımın başlangıç dizilişi');const away=document.createElement('div');away.className='formation-half away-half';for(const i of [0,5,4,1,2,3])away.append(token(MatchIntro.opponents(fixture)[i],null,true,i));const net=document.createElement('div');net.className='formation-net';net.textContent='MAHALLE LİGİ · '+fixture.round+'. MAÇ';const own=document.createElement('div');own.className='formation-half own-half';for(const [i,slot]of ['o2','p','s1','s2','pc','o1'].entries())own.append(token(squad.players.find(p=>p.id===draft[slot]),slot,false,i));court.append(away,net,own);const homeName=document.createElement('h3');homeName.textContent=LeagueRules.teams[0];const libero=document.createElement('button');libero.type='button';libero.className='formation-libero';libero.dataset.slot='l';const l=squad.players.find(p=>p.id===draft.l);libero.textContent='LİBERO · '+(l?l.name+' '+l.surname:'Oyuncu seç');libero.onclick=()=>choose('l');stage.append(awayName,court,homeName,libero);}
function choose(slot,focus=true){selected=slot;const box=$('preMatchPicker'),role=TeamRules.slots.find(s=>s.id===slot),squad=TeamView.snapshot();box.replaceChildren();box.hidden=false;const heading=document.createElement('strong');heading.textContent=role.name+' · Son hazırlık';heading.tabIndex=-1;const close=document.createElement('button');close.type='button';close.textContent='Kapat';close.className='formation-picker-close';close.onclick=()=>{box.hidden=true;document.querySelector('#preMatchStage [data-slot="'+slot+'"]').focus()};box.append(heading,close);trainingPanel(box,slot);const benchLabel=document.createElement("p");benchLabel.className="prematch-bench-label";benchLabel.textContent="Oyuncuyu değiştir";box.append(benchLabel);for(const p of squad.players.filter(p=>p.role===role.role)){const b=document.createElement('button');b.type='button';b.className='formation-option';b.setAttribute('aria-pressed',String(draft[slot]===p.id));const name=document.createElement('strong');name.textContent=p.name+' '+p.surname;const info=document.createElement('small');info.textContent='Smaç '+p.spike+' · Manşet '+p.receive+' · Pas '+p.set+' · Blok '+p.block;b.append(name,info);b.onclick=()=>{const previous=draft[slot],other=Object.keys(draft).find(k=>k!==slot&&draft[k]===p.id);if(other)draft[other]=previous;draft[slot]=p.id;render();box.hidden=true;$('preMatchNotice').textContent=p.name+' '+role.name+' pozisyonunda.';document.querySelector('#preMatchStage [data-slot="'+slot+'"]').focus()};box.append(b)}if(focus)heading.focus({preventScroll:true});if(focus)box.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'});}
function trainingPanel(box,slot){
 const p=TeamRules.players.find(p=>p.id===draft[slot]);if(!p)return;
 const panel=document.createElement('section');panel.className='prematch-training';
 const head=document.createElement('div');head.className='prematch-player-heading';const portrait=document.createElement('img');portrait.src=TeamAppearance.portrait(p.appearance);portrait.alt='';const name=document.createElement('strong');name.textContent=p.name+' '+p.surname;const summary=document.createElement('small');summary.textContent='OVR '+TeamRules.overall(p);const wallet=document.createElement('div');wallet.className='prematch-ap-wallet';const amount=document.createElement('b'),caption=document.createElement('span');amount.textContent=Math.floor(RoomSystem.balance()).toLocaleString('tr-TR')+' AP';caption.textContent='Kullanılabilir';wallet.append(caption,amount);head.append(portrait,name,summary);panel.append(wallet);panel.append(head);
 panel.append(CardUpgrade.panel(p,result=>{TeamView.refresh();render();choose(slot,false);$('preMatchNotice').textContent='Kart seviyesi '+result.level+(result.free?' · Ücretsiz!':'')}));box.append(panel)

}
window.PreMatch={open(f){fixture=f;draft={...TeamView.snapshot().lineup};selected=null;$('preMatchPicker').hidden=true;$('preMatchNotice').textContent='Oyuncuya dokun: geliştir veya değiştir.';render(true)},editFirst(){choose('p')},commit(){if(TeamRules.slots.some(s=>!draft[s.id])){$('preMatchNotice').textContent='6 oyuncu ve libero seçmelisin.';choose(TeamRules.slots.find(s=>!draft[s.id]).id);return false}if(!TeamView.commitMatchLineup(draft)){$('preMatchNotice').textContent='Kadro kaydedilemedi. Yeniden dene.';return false}return true}};
})();
