(function(){
'use strict';const $=id=>document.getElementById(id),KEY='idle-spiker-rooms-v2';let state=RoomRules.defaults(),selection=null,lastTrigger=null,autoClick=null,lastTick=Date.now(),lastSave=0;
try{const raw=localStorage.getItem(KEY);state=raw?RoomRules.normalize(JSON.parse(raw)):RoomRules.migrate(JSON.parse(localStorage.getItem('idle-spiker-rooms-v1')))}catch{}
const fmt=n=>n.toLocaleString('tr-TR',{maximumFractionDigits:1});
function save(){if(window.gameResetting)return;try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}}
function stats(){window.TeamView?.refreshAP?.();const e=RoomRules.effects(state);$('roomBudget').textContent=fmt(state.budget);$('roomAP').textContent=fmt(state.ap);$('roomPower').textContent=fmt(e.clickAP);$('roomAuto').textContent=fmt(e.autoRate);document.querySelectorAll('.unlock-room').forEach(b=>{const f=Number(b.dataset.floor),price=RoomRules.cost(state,f);b.disabled=state.budget<price;b.querySelector('small').textContent=price+' bütçe'+(b.disabled?' · '+fmt(price-state.budget)+' eksik':'')})}
function upgradeStats(){document.querySelectorAll('.upgrade-room').forEach(b=>{const room=RoomRules.catalog.find(r=>r.id===b.dataset.id),n=RoomRules.count(state,room.id),price=RoomRules.cost(state,room.floor);b.disabled=n>=3||state.budget<price;b.querySelector('.room-active').textContent=n>=3?'SEVİYE 3 · MAKSİMUM':'SEVİYE '+n+' · ↑ '+price+' BÜTÇE';b.title=n>=3?'En yüksek seviyede':room.describe(room.values[n])+(state.budget<price?' · '+fmt(price-state.budget)+' bütçe eksik':'')})}
function openPicker(floor,index,trigger){selection={floor,index};lastTrigger=trigger;$('roomSelectionInfo').textContent=RoomRules.departments[floor]+' · Yeni blok';$('roomChoices').replaceChildren(...RoomRules.catalog.filter(r=>r.floor===floor).map(room=>{const n=RoomRules.count(state,room.id),b=document.createElement('button');b.className='room-choice';b.disabled=n>0;const icon=document.createElement('span'),text=document.createElement('span'),name=document.createElement('strong'),desc=document.createElement('small');icon.textContent=room.icon;name.textContent=room.name;desc.textContent=n?'Zaten kurulu · Kartına dokunarak yükselt':room.describe(room.values[0]);text.append(name,desc);b.append(icon,text);b.onclick=()=>{if(selection&&RoomRules.choose(state,selection.floor,selection.index,room.id)){save();render();$('roomDialog').close();window.MenuFeedback?.build(room.name)}};return b}));if(!$('roomDialog').open)$('roomDialog').showModal()}
function render(){for(let floor=0;floor<5;floor++){const slot=$('roomSlots'+floor),row=state.floors[floor],seen={};const cards=row.map((id,index)=>{if(id!==null&&row.indexOf(id)!==index)return null;if(id===null){const b=document.createElement('button');b.className='room-tile empty-room';b.innerHTML='<span class="slot-icon">＋</span><strong>Blok seç</strong><small>Alan hazır</small>';b.onclick=()=>openPicker(floor,index,b);return b}const room=RoomRules.catalog.find(r=>r.id===id),card=document.createElement('button'),copy=seen[id]=(seen[id]||0)+1;card.className='room-tile purchased-room upgrade-room room-'+id;card.dataset.id=id;card.onclick=()=>{if(RoomRules.upgrade(state,id)){save();render();window.MenuFeedback?.build(room.name+' · Seviye '+RoomRules.count(state,id))}};const icon=document.createElement('span'),title=document.createElement('strong'),description=document.createElement('small'),badge=document.createElement('span');icon.className='slot-icon';icon.textContent=room.icon;title.textContent=room.name;description.textContent=room.describe(room.values[RoomRules.count(state,id)-1]);badge.className='room-active';badge.textContent=copy+'. KOPYA · TOPLAM SEVİYE '+RoomRules.count(state,id)+'/3';card.append(icon,title,description,badge);return card}).filter(Boolean);if(!row.includes(null)&&RoomRules.catalog.some(r=>r.floor===floor&&!RoomRules.count(state,r.id))&&row.length<(floor===4?6:9)){const b=document.createElement('button');b.className='room-tile unlock-room';b.dataset.floor=floor;b.innerHTML='<span class="slot-icon">＋</span><strong>Yeni alan aç</strong><small></small>';b.onclick=()=>{if(RoomRules.unlock(state,floor)){save();render();const next=$('roomSlots'+floor).querySelector('.empty-room');next.scrollIntoView({block:'nearest',inline:'center',behavior:'smooth'});openPicker(floor,state.floors[floor].length-1,next)}};cards.push(b)}slot.replaceChildren(...cards)}const e=RoomRules.effects(state);$('boostSlots').replaceChildren(...Array.from({length:e.slots},(_,i)=>{const s=document.createElement('span');s.className='boost-slot';s.textContent='◇ Boost '+(i+1)+' · Boş';return s}));stats();upgradeStats()}
function settleOffline(){if(window.gameResetting)return;const gain=RoomRules.offline(state,Date.now());if(gain>0){$('offlineNotice').hidden=false;$('offlineNotice').textContent='Tekrar hoş geldin! Asistanın +'+fmt(gain)+' AP biriktirdi.'}save();stats()}
$('closeRoom').onclick=()=>$('roomDialog').close();$('roomDialog').addEventListener('close',()=>{if(lastTrigger?.isConnected)lastTrigger.focus();else $('energyButton').focus();selection=null});
window.RoomSystem={prepareReset(){state=RoomRules.defaults();autoClick=null;lastTick=Date.now();render()},balance:()=>state.ap,spendAP(amount){if(!Number.isFinite(amount)||amount<=0||state.ap<amount)return false;state.ap-=amount;save();stats();return true},onClick(completed){const result=RoomRules.income(state,completed);state.lastSeen=Date.now();save();stats();upgradeStats();$('apFeedback').textContent=(result.critical?'KRİTİK! ':'')+'+'+fmt(result.ap)+' AP';return result},effects:()=>RoomRules.effects(state),setAutoClick(fn){autoClick=fn}};
render();settleOffline();
setInterval(()=>{if(window.gameResetting)return;const now=Date.now();if(document.hidden){lastTick=now;return}if(window.MatchGateway?.active()){lastTick=now;state.lastSeen=now;return}const dt=Math.max(0,(now-lastTick)/1000);lastTick=now;if(dt>5){settleOffline();return}if(autoClick){state.autoCarry+=dt*RoomRules.effects(state).autoRate;const clicks=Math.floor(state.autoCarry);state.autoCarry-=clicks;for(let i=0;i<clicks;i++)autoClick()}state.lastSeen=now;if(now-lastSave>5000){save();lastSave=now}},250);
document.addEventListener('visibilitychange',()=>{if(document.hidden){state.lastSeen=Date.now();save()}else{settleOffline();lastTick=Date.now()}});window.addEventListener('pagehide',()=>{if(!document.hidden)state.lastSeen=Date.now();save()});
window.addEventListener('storage',e=>{if(e.key===KEY){try{state=RoomRules.normalize(JSON.parse(e.newValue));lastTick=Date.now();render()}catch{}}});
})();
