(function(){
'use strict';const R=TeamRules,$=id=>document.getElementById(id),key='idle-spiker-team-v1';let lineup=R.defaults(),selected=null,desired=null,trigger=null;try{const saved=localStorage.getItem(key);if(saved)lineup=R.normalize(JSON.parse(saved))}catch{}
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let appearances={};try{appearances=JSON.parse(localStorage.getItem('idle-spiker-appearance-v2')||'{}')}catch{}for(const p of R.players){if(!TeamAppearance.valid(appearances[p.id]))appearances[p.id]=TeamAppearance.generate();p.appearance=appearances[p.id];p.art=TeamAppearance.portrait(p.appearance)}try{localStorage.setItem('idle-spiker-appearance-v2',JSON.stringify(appearances))}catch{}
const stats=[['spike','Smaç','Smaçla sayı alma gücü.'],['block','Blok','Rakip smaçları durdurma gücü.'],['serve','Servis','Servisle rakibi zorlama gücü.'],['receive','Manşet','Servis ve smaçları karşılama gücü.'],['set','Oyun Kurma ve Pas','Hücumcuya atılan pasın kalitesi.'],['height','Boy','Smaç ve blokta boy avantajı.'],['stamina','Dayanıklılık','Yorulmaya karşı direnç.'],['mental','Mental','Baskı altında performansı koruma.']];
function card(p){const b=document.createElement('div');b.className='player-card role-'+p.role;b.dataset.player=p.id;b.setAttribute('aria-label',p.name+', '+R.roles[p.role]+', kartı incele');b.innerHTML='<div class="card-top"><span>'+R.roles[p.role]+'</span><b>#'+p.number+'</b></div><div class="card-art"><span class="card-halo"></span><span class="player-overall" title="Pozisyonuna göre genel güç puanı" aria-label="Genel oyuncu puanı '+R.overall(p)+'"><b>'+R.overall(p)+'</b><small>OVR</small></span><img src="'+p.art+'" alt="'+escape(p.name)+'" loading="lazy"></div><div class="card-name"><button class="card-inspect" type="button">'+escape(p.name)+'<small>'+escape(p.surname)+'</small></button><button class="name-pencil" type="button" aria-label="Ad soyad düzenle">✎</button></div><small class="card-cap">Seviye '+R.cardLevel(p)+' / '+R.cardLimit(p)+' · Stat sınırı '+R.cap(p)+'</small><div class="card-stats">'+stats.slice(0,5).map(([k,label])=>'<span><em>'+label+'</em><b>'+p[k]+(p[k]>p.baseStats[k]?'<small class="stat-gain"> +'+(p[k]-p.baseStats[k])+'</small>':'')+'</b><i style="--stat:'+(p[k]/R.cap(p)*100)+'%"></i></span>').join('')+'</div><div class="card-physical"><span>'+p.height+' cm</span><span>DAY '+p.stamina+'</span><span>MEN '+p.mental+'</span></div><button class="card-open-upgrade" type="button"><span>↑ Hızlı Yükselt</span><small></small></button>';b.onclick=e=>{if(e.target.closest('.name-pencil')){editName(p);return}if(e.target.closest('.card-open-upgrade')){let free=false;if(R.upgradeCard(p,cost=>{const paid=RoomSystem.payTraining(cost);free=paid.free;return paid.ok})){render();$('teamNotice').textContent=p.name+' · Seviye '+R.cardLevel(p)+(free?' · Ücretsiz yükseltme!':'');const updated=document.querySelector('[data-player="'+p.id+'"]');updated?.querySelector('.card-open-upgrade')?.focus({preventScroll:true});window.GameAudio?.uiClick();if(updated){updated.classList.add('quick-upgraded');setTimeout(()=>updated.classList.remove('quick-upgraded'),650);const action=updated.querySelector('.card-open-upgrade');if(!matchMedia('(prefers-reduced-motion: reduce)').matches){action?.animate([{transform:'translateY(3px) scale(.97)'},{transform:'translateY(-1px) scale(1.015)',offset:.6},{transform:'none'}],{duration:230,easing:'ease-out'});if(navigator.vibrate)navigator.vibrate(8)}}if(updated&&!matchMedia('(prefers-reduced-motion: reduce)').matches)updated.animate([{filter:'brightness(1.25)'},{filter:'brightness(1)'}],{duration:600})}return}detail(p,b.querySelector('.card-inspect'))};return b}
function refreshAP(){document.querySelectorAll('.player-card').forEach(card=>{const p=R.players.find(p=>p.id===card.dataset.player),q=R.cardQuote(p);card.dataset.canUpgrade=String(!q.blocked&&(window.RoomSystem?.balance()||0)>=q.cost);const action=card.querySelector('.card-open-upgrade');action.querySelector('span').textContent=q.blocked?'✓ Seviye tamamlandı':'↑ Hızlı Yükselt';action.querySelector('small').textContent=q.blocked?'En yüksek seviye':q.cost.toLocaleString('tr-TR')+' AP';action.disabled=!!q.blocked||(window.RoomSystem?.balance()||0)<q.cost;action.setAttribute('aria-label',p.name+' · '+(q.blocked?'En yüksek seviye':'Hızlı Yükselt · '+q.cost+' AP'))});const ap=window.RoomSystem?.balance()||0;document.querySelectorAll('.card-upgrade-button[data-ap-cost]').forEach(b=>b.disabled=ap<Number(b.dataset.apCost));document.querySelectorAll('.prematch-ap-wallet b').forEach(b=>b.textContent=Math.floor(ap).toLocaleString('tr-TR')+' AP');if(!selected||!$('playerDialog').open)return;$('trainingBalance').textContent=Math.floor(ap).toLocaleString('tr-TR')+' AP';document.querySelectorAll('[data-ap-cost]').forEach(b=>{b.disabled=ap<Number(b.dataset.apCost)})}
function renderDevelopment(){const p=selected,labels=Object.fromEntries(stats.map(s=>[s[0],s[1]]));
 document.querySelector('.development-note').innerHTML='<strong>'+R.stageLabel()+' · Stat sınırı '+R.cap(p)+'</strong><span>Kartını yükselt; özellikleri pozisyonuna göre birlikte gelişsin.</span>';
 $('trainingStats').replaceChildren(CardUpgrade.panel(p,result=>{render();detail(p,trigger);$('trainingNotice').textContent=(result.free?'İlham Anı! Ücretsiz yükseldi · ':'')+'Kart seviyesi '+result.level}));
 $('playerSkills').replaceChildren(...p.skills.map(owned=>{const skill=R.skillCatalog.find(s=>s.id===owned.id),box=document.createElement('div');box.className='skill-card'+(owned.unlocked?' unlocked':'')+(!skill.basic?' future-skill':'');const title=document.createElement('strong'),desc=document.createElement('small'),b=document.createElement('button');title.textContent=skill.name;desc.textContent=skill.basic?labels[skill.stat]+' +2 · Stat sınırını aşmaz · Bir yetenek seç':'İleri yetenek · Prologda kapalı';const blocked=R.skillBlock(p,skill.id);b.textContent=owned.unlocked?'✓ Açıldı':blocked||'Seç · '+R.skillCost(p,skill.id)+' AP';b.disabled=!!blocked;if(!blocked)b.dataset.apCost=R.skillCost(p,skill.id);b.onclick=()=>{if(R.unlockSkill(p,skill.id,amount=>window.RoomSystem.spendAP(amount))){$('trainingNotice').textContent=skill.name+' açıldı!';render();detail(p,trigger);window.MenuFeedback?.build(skill.name)}};box.append(title,desc,b);return box}));refreshAP();const ap=window.RoomSystem?.balance()||0;$('trainingBalance').textContent=Math.floor(ap)+' AP';document.querySelectorAll('[data-ap-cost]').forEach(b=>b.disabled=ap<Number(b.dataset.apCost))}
function save(){try{localStorage.setItem(key,JSON.stringify(lineup));$('teamNotice').textContent='Kadro kaydedildi.';setTimeout(()=>window.MatchGateway?.resumeIfReady(),0)}catch{$('teamNotice').textContent='Kadro bu oturumda güncellendi; tarayıcı kaydetmeye izin vermedi.'}}
function render(){document.querySelector('#teamPanel .team-hint').textContent=R.stageLabel()+' · AP ile kartlarını yükselt.';const assigned=new Set(Object.values(lineup));$('activeTeam').replaceChildren(...R.slots.map(s=>{const box=document.createElement('div');box.className='team-slot'+(s.role==='libero'?' libero-slot':'');const label=document.createElement('div');label.className='slot-label';label.textContent=s.name;box.append(label);const p=R.players.find(p=>p.id===lineup[s.id]);if(p)box.append(card(p));else{const b=document.createElement('button');b.className='empty-player';b.innerHTML='<b>＋</b><span>Oyuncu seç</span>';b.onclick=()=>{desired=s.id;$('benchFilter').value=s.role;renderBench();$('benchSection').scrollIntoView({behavior:'smooth',block:'start'});$('teamNotice').textContent=s.name+' için bir yedek seç.'};box.append(b)}return box}));$('teamCount').textContent=assigned.size-(assigned.has(null)?1:0)+' / 7';renderBench();refreshAP()}
function renderBench(){const used=new Set(Object.values(lineup)),role=$('benchFilter').value;const bench=R.players.filter(p=>!used.has(p.id));$('benchCount').textContent=bench.length+' kart';const list=bench.filter(p=>role==='all'||p.role===role);$('benchCards').replaceChildren(...list.map(card));$('benchEmpty').hidden=list.length>0}
function detail(p,button){selected=p;trigger=button;$('playerName').textContent=p.name+' '+p.surname;$('playerRole').textContent=R.roles[p.role];$('detailArt').src=p.art;$('detailArt').alt=p.name;$('playerStats').replaceChildren(...stats.map(([k,label,explain])=>{const item=document.createElement('div');item.className='detail-stat';item.innerHTML='<div><strong>'+label+'</strong><b>'+p[k]+(k==='height'?' cm':' / '+R.cap(p))+'</b></div><p>'+explain+'</p>';return item}));const choices=R.slots.filter(s=>s.role===p.role);$('equipSlot').replaceChildren(...choices.map(s=>{const option=document.createElement('option'),current=R.players.find(p=>p.id===lineup[s.id]);option.value=s.id;option.textContent=s.name+' · '+(current?current.name+' '+current.surname:'Boş');return option}));if(choices.some(s=>s.id===desired))$('equipSlot').value=desired;else{const current=choices.find(s=>lineup[s.id]===p.id);if(current)$('equipSlot').value=current.id}$('benchPlayer').hidden=!Object.values(lineup).includes(p.id);$('equipPlayer').textContent=Object.values(lineup).includes(p.id)?'Slota yerleştir':'Kadroya al';renderDevelopment();if(!$('playerDialog').open){$('playerAttributes').open=true;$('playerDialog').showModal()}}
$('equipPlayer').onclick=()=>{if(selected&&R.equip(lineup,$('equipSlot').value,selected.id)){save();render();$('playerDialog').close();desired=null}};$('benchPlayer').onclick=()=>{for(const s of R.slots)if(lineup[s.id]===selected?.id)lineup[s.id]=null;save();render();$('playerDialog').close()};$('closePlayer').onclick=()=>$('playerDialog').close();$('playerDialog').addEventListener('close',()=>{if(trigger?.isConnected)trigger.focus();else $('teamTab').focus()});$('benchFilter').onchange=renderBench;
function showTeam(show){document.body.classList.toggle('team-open',show);$('teamPanel').hidden=!show;document.querySelector('.dashboard').hidden=show;$('teamTab').setAttribute('aria-current',show?'page':'false');if(show){render();window.scrollTo({top:0,behavior:'instant'})}}
function editName(p){$('renameId').value=p.id;$('firstName').value=p.name;$('lastName').value=p.surname;$('renameDialog').showModal();$('firstName').focus()}
$('renameForm').onsubmit=e=>{e.preventDefault();if(R.rename($('renameId').value,$('firstName').value,$('lastName').value)){render();$('renameDialog').close();$('teamNotice').textContent='Oyuncu adı kaydedildi.'}};$('cancelRename').onclick=()=>$('renameDialog').close();
window.TeamView={commitMatchLineup(draft){const next=R.normalize(draft);if(R.slots.some(s=>!next[s.id]||next[s.id]!==draft[s.id]))return false;try{localStorage.setItem(key,JSON.stringify(next))}catch{return false}lineup=next;render();return true;},refresh(){render();if(selected&&$('playerDialog').open)detail(selected,trigger)},refreshAP,close:()=>showTeam(false),snapshot:()=>({lineup:{...lineup},players:R.players.map(p=>({...p,art:undefined}))})};
$('teamTab').onclick=e=>{e.preventDefault();showTeam(true)};document.querySelectorAll('.mobile-nav a:not(#teamTab)').forEach(a=>a.addEventListener('click',()=>showTeam(false)));window.addEventListener('storage',e=>{if(e.key===key){try{lineup=R.normalize(JSON.parse(e.newValue));render()}catch{}}});render();
})();
