(function(){
'use strict';const R=TeamRules,$=id=>document.getElementById(id),key='idle-spiker-team-v1';let lineup=R.defaults(),selected=null,desired=null,trigger=null;try{const saved=localStorage.getItem(key);if(saved)lineup=R.normalize(JSON.parse(saved))}catch{}
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let appearances={};try{appearances=JSON.parse(localStorage.getItem('idle-spiker-appearance-v2')||'{}')}catch{}for(const p of R.players){if(!TeamAppearance.valid(appearances[p.id]))appearances[p.id]=TeamAppearance.generate();p.appearance=appearances[p.id];p.art=TeamAppearance.portrait(p.appearance)}try{localStorage.setItem('idle-spiker-appearance-v2',JSON.stringify(appearances))}catch{}
const stats=[['spike','Smaç','Hücum gücü; rakip bloğu aşma ve sayı alma yeteneği.'],['block','Blok','Rakibin hücumunu durdurma ve topu rakip sahaya düşürme yeteneği.'],['serve','Servis','Rakip manşeti bozma ve doğrudan sayı alma yeteneği.'],['receive','Manşet','Servis ve smaçları karşılayarak topu oyunda tutma gücü.'],['set','Oyun kurma','Hücumcuya verilen pasın kalitesi.'],['height','Boy','Smaç ve blok için fiziksel avantaj.'],['stamina','Dayanıklılık','Uzun maçlarda performansı koruma.'],['mental','Mental','Baskı altında oyunda kalma ve takım momentumu.']];
function card(p){const b=document.createElement('div');b.className='player-card role-'+p.role;b.setAttribute('aria-label',p.name+', '+R.roles[p.role]+', kartı incele');b.innerHTML='<div class="card-top"><span>'+R.roles[p.role]+'</span><b>#'+p.number+'</b></div><div class="card-art"><span class="card-halo"></span><img src="'+p.art+'" alt="'+escape(p.name)+'" loading="lazy"></div><div class="card-name"><button class="card-inspect" type="button">'+escape(p.name)+'<small>'+escape(p.surname)+'</small></button><button class="name-pencil" type="button" aria-label="Ad soyad düzenle">✎</button></div><div class="card-stats">'+stats.slice(0,5).map(([k,label])=>'<span><em>'+label+'</em><b>'+p[k]+(p[k]>p.baseStats[k]?'<small class="stat-gain"> +'+(p[k]-p.baseStats[k])+'</small>':'')+'</b><i style="--stat:'+(p[k]/35*100)+'%"></i></span>').join('')+'</div><div class="card-physical"><span>'+p.height+' cm</span><span>DAY '+p.stamina+'</span><span>MEN '+p.mental+'</span></div>';b.querySelector('.card-inspect').onclick=()=>detail(p,b.querySelector('.card-inspect'));b.querySelector('.name-pencil').onclick=()=>editName(p);b.querySelector('.card-art').onclick=()=>detail(p,b.querySelector('.card-inspect'));return b}
function refreshAP(){if(!selected||!$('playerDialog').open)return;const ap=window.RoomSystem?.balance()||0;$('trainingBalance').textContent=Math.floor(ap).toLocaleString('tr-TR')+' AP';document.querySelectorAll('[data-ap-cost]').forEach(b=>{b.disabled=ap<Number(b.dataset.apCost)})}
function renderDevelopment(){const p=selected,labels=Object.fromEntries(stats.map(s=>[s[0],s[1]])),used=R.growth(p);
 document.querySelector('.development-note').innerHTML='<strong>MAHALLE LİGİ · '+used+' / 24 gelişim</strong><progress max="24" value="'+used+'" aria-label="Kullanılan gelişim puanı"></progress><span>Her artış 1 hak kullanır. En fazla 2 özellik 28’i aşabilir; üst sınır 35. Bir temel yetenek seçebilirsin.</span><small>Bu bölüm bir başlangıç. İleride kendi takımını kuracaksın.</small>';
 $('trainingStats').replaceChildren(...R.trainable.map(k=>{const row=document.createElement('div');row.className='training-row';const title=document.createElement('span'),gain=p[k]-p.baseStats[k];title.innerHTML='<strong>'+labels[k]+' · '+p[k]+' / 100</strong><small>Başlangıç '+p.baseStats[k]+(gain?' · +'+gain+' gelişti':' · Gelişime açık')+'</small><progress max="35" value="'+p[k]+'" aria-label="'+labels[k]+', bu bölümün sınırı 35"></progress>';const b=document.createElement('button'),blocked=R.trainingBlock(p,k);b.className='train-button';b.textContent=blocked?'Sınıra ulaştı':'+1 · '+R.statCost(p,k)+' AP';b.title=blocked||'Bir gelişim hakkı kullanır.';if(!blocked)b.dataset.apCost=R.statCost(p,k);else b.disabled=true;b.onclick=()=>{if(R.train(p,k,amount=>window.RoomSystem.spendAP(amount))){$('trainingNotice').textContent=labels[k]+' '+(p[k]-1)+' → '+p[k];render();detail(p,trigger);window.MenuFeedback?.build(labels[k]+' +1')}};row.append(title,b);if(blocked){const note=document.createElement('small');note.className='training-limit';note.textContent=blocked;row.append(note)}return row}));
 $('playerSkills').replaceChildren(...p.skills.map(owned=>{const skill=R.skillCatalog.find(s=>s.id===owned.id),box=document.createElement('div');box.className='skill-card'+(owned.unlocked?' unlocked':'')+(!skill.basic?' future-skill':'');const title=document.createElement('strong'),desc=document.createElement('small'),b=document.createElement('button');title.textContent=skill.name;desc.textContent=skill.basic?labels[skill.stat]+' +2 · 2 gelişim hakkı · Tek yetenek seçimi':'İleri teknik · Bu bölümde kullanılamaz';const blocked=R.skillBlock(p,skill.id);b.textContent=owned.unlocked?'✓ Açıldı':blocked||'Seç · '+skill.cost+' AP';b.disabled=!!blocked;if(!blocked)b.dataset.apCost=skill.cost;b.onclick=()=>{if(R.unlockSkill(p,skill.id,amount=>window.RoomSystem.spendAP(amount))){$('trainingNotice').textContent=skill.name+' açıldı!';render();detail(p,trigger);window.MenuFeedback?.build(skill.name)}};box.append(title,desc,b);return box}));refreshAP();const ap=window.RoomSystem?.balance()||0;$('trainingBalance').textContent=Math.floor(ap)+' AP';document.querySelectorAll('[data-ap-cost]').forEach(b=>b.disabled=ap<Number(b.dataset.apCost))}
function save(){try{localStorage.setItem(key,JSON.stringify(lineup));$('teamNotice').textContent='Kadro kaydedildi.';setTimeout(()=>window.MatchGateway?.resumeIfReady(),0)}catch{$('teamNotice').textContent='Kadro bu oturumda güncellendi; tarayıcı kaydetmeye izin vermedi.'}}
function render(){const assigned=new Set(Object.values(lineup));$('activeTeam').replaceChildren(...R.slots.map(s=>{const box=document.createElement('div');box.className='team-slot'+(s.role==='libero'?' libero-slot':'');const label=document.createElement('div');label.className='slot-label';label.textContent=s.name;box.append(label);const p=R.players.find(p=>p.id===lineup[s.id]);if(p)box.append(card(p));else{const b=document.createElement('button');b.className='empty-player';b.innerHTML='<b>＋</b><span>Oyuncu seç</span>';b.onclick=()=>{desired=s.id;$('benchFilter').value=s.role;renderBench();$('benchSection').scrollIntoView({behavior:'smooth',block:'start'});$('teamNotice').textContent=s.name+' için bir yedek seç.'};box.append(b)}return box}));$('teamCount').textContent=assigned.size-(assigned.has(null)?1:0)+' / 7';renderBench()}
function renderBench(){const used=new Set(Object.values(lineup)),role=$('benchFilter').value;const bench=R.players.filter(p=>!used.has(p.id));$('benchCount').textContent=bench.length+' kart';const list=bench.filter(p=>role==='all'||p.role===role);$('benchCards').replaceChildren(...list.map(card));$('benchEmpty').hidden=list.length>0}
function detail(p,button){selected=p;trigger=button;$('playerName').textContent=p.name+' '+p.surname;$('playerRole').textContent=R.roles[p.role];$('detailArt').src=p.art;$('detailArt').alt=p.name;$('playerStats').replaceChildren(...stats.map(([k,label,explain])=>{const item=document.createElement('div');item.className='detail-stat';item.innerHTML='<div><strong>'+label+'</strong><b>'+p[k]+(k==='height'?' cm':' / 100')+'</b></div><p>'+explain+'</p>';return item}));const choices=R.slots.filter(s=>s.role===p.role);$('equipSlot').replaceChildren(...choices.map(s=>{const option=document.createElement('option'),current=R.players.find(p=>p.id===lineup[s.id]);option.value=s.id;option.textContent=s.name+' · '+(current?current.name+' '+current.surname:'Boş');return option}));if(choices.some(s=>s.id===desired))$('equipSlot').value=desired;else{const current=choices.find(s=>lineup[s.id]===p.id);if(current)$('equipSlot').value=current.id}$('benchPlayer').hidden=!Object.values(lineup).includes(p.id);$('equipPlayer').textContent=Object.values(lineup).includes(p.id)?'Slota yerleştir':'Kadroya al';renderDevelopment();if(!$('playerDialog').open)$('playerDialog').showModal()}
$('equipPlayer').onclick=()=>{if(selected&&R.equip(lineup,$('equipSlot').value,selected.id)){save();render();$('playerDialog').close();desired=null}};$('benchPlayer').onclick=()=>{for(const s of R.slots)if(lineup[s.id]===selected?.id)lineup[s.id]=null;save();render();$('playerDialog').close()};$('closePlayer').onclick=()=>$('playerDialog').close();$('playerDialog').addEventListener('close',()=>{if(trigger?.isConnected)trigger.focus();else $('teamTab').focus()});$('benchFilter').onchange=renderBench;
function showTeam(show){document.body.classList.toggle('team-open',show);$('teamPanel').hidden=!show;document.querySelector('.dashboard').hidden=show;$('teamTab').setAttribute('aria-current',show?'page':'false');if(show){render();window.scrollTo({top:0,behavior:'instant'})}}
function editName(p){$('renameId').value=p.id;$('firstName').value=p.name;$('lastName').value=p.surname;$('renameDialog').showModal();$('firstName').focus()}
$('renameForm').onsubmit=e=>{e.preventDefault();if(R.rename($('renameId').value,$('firstName').value,$('lastName').value)){render();$('renameDialog').close();$('teamNotice').textContent='Oyuncu adı kaydedildi.'}};$('cancelRename').onclick=()=>$('renameDialog').close();
window.TeamView={refreshAP,close:()=>showTeam(false),snapshot:()=>({lineup:{...lineup},players:R.players.map(p=>({...p,art:undefined}))})};
$('teamTab').onclick=e=>{e.preventDefault();showTeam(true)};document.querySelectorAll('.mobile-nav a:not(#teamTab)').forEach(a=>a.addEventListener('click',()=>showTeam(false)));window.addEventListener('storage',e=>{if(e.key===key){try{lineup=R.normalize(JSON.parse(e.newValue));render()}catch{}}});render();
})();
