const fs=require('fs'),vm=require('vm'),assert=require('assert');
let script=fs.readFileSync('deneme-modu.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1];script=script.replace(/init\(\);\s*$/,'');
const elements={},context={console,assert,Math,document:{getElementById:id=>elements[id]??={value:id==='mistakes'?'35':'1',getContext:()=>({})}}};
vm.createContext(context);vm.runInContext(script,context);
vm.runInContext(`reset();ready=true;for(let i=0;i<18000;i++)tick(1/60);
assert.equal(players.length,12);assert(history.some(e=>e.type==='drop'));assert(scores[0]+scores[1]+sets[0]+sets[1]>0);
const contacts=history.filter(e=>e.type==='touch');assert.deepEqual(contacts.slice(0,3).map(e=>e.touch),[1,2,3]);
for(let i=1;i<history.length;i++){const a=history[i-1],b=history[i];if(a.type==='touch'&&b.type==='touch'){assert.equal(b.touch,a.touch===3?1:a.touch+1);assert.equal(b.team,a.touch===3?1-a.team:a.team)}}
const before=JSON.stringify([players,ball]);paused=true;tick(10);assert.equal(JSON.stringify([players,ball]),before);
assert(LAYOUT.length===7);assert(LAYOUT.some(p=>p.path==='arm_jersey.png'));console.log('PASS: 5 simulated minutes, 12 players, 3-touch sequence, side changes, drops, scoring, pause, approved 7-piece character.');`,context);
vm.runInContext(`reset();const zones=players.map(p=>p.zone);awardPoint(0);assert.equal(servingTeam,0);assert.deepEqual(players.map(p=>p.zone),zones);awardPoint(1);assert.equal(servingTeam,1);assert.equal(rotationCount[1],1);for(const p of players.filter(p=>p.team===1))assert.equal(p.zone,zones[p.index]===1?6:zones[p.index]-1);assert.equal(serverPlayer().zone,1);const server=serverPlayer().index;awardPoint(1);assert.equal(serverPlayer().index,server);assert.equal(rotationCount[1],1);scores=[24,24];awardPoint(0);assert.equal(sets[0],0);awardPoint(0);assert.equal(sets[0],1);assert.equal(scores[0],0);console.log('PASS: side-out-only rotation, correct server, repeated serve, 25-point set and two-point margin.');`,context);
assert(script.includes("if(part.id.startsWith('arm-')&&!p.moving&&!(p.block>0)&&!(p.spike>0)&&!approachingSpike(p)&&!tossing(p))continue;"));

vm.runInContext(`assert.equal(playerLayout({block:0}),LAYOUT);assert.equal(playerLayout({block:.5}),BLOCK_LAYOUT);assert.equal(playerLayout({block:.5})[0].id,'sleeve-left');assert.equal(playerLayout({block:.5}).find(p=>p.id==='sleeve-right').y,28.576950915941936);assert.notEqual(LAYOUT.find(p=>p.id==='sleeve-right').y,BLOCK_LAYOUT.find(p=>p.id==='sleeve-right').y);console.log('PASS: block pose selection, exact imported coordinates/layers, normal pose preserved.');`,context);

vm.runInContext(`reset();ready=true;paused=false;const beforePlayers=players,beforeBall=ball,beforeScore=JSON.stringify(scores);for(const kind of ["block","toss","serve","spike"]){beginScenario(kind);assert.equal(scenario.kind,kind);tick(.9);assert(Number.isFinite(ball.x));assert(Number.isFinite(ball.z));if(kind==="block")assert(players.some(p=>p.block>0));const t=scenario.time;paused=true;tick(.2);assert.equal(scenario.time,t);paused=false;tick(4);assert.equal(JSON.stringify(scores),beforeScore);}endScenario();assert.equal(players,beforePlayers);assert.equal(ball,beforeBall);assert.equal(scenario,null);console.log("PASS: all 4 scenario buttons, block pose, pause, repetition, score isolation and match restoration.");`,context);

vm.runInContext(`assert.equal(playerLayout({spike:.5}),SPIKE_LAYOUT);assert.equal(spikeAngle(.65),-Math.PI);assert(Math.abs(spikeAngle(.26)+Math.PI/2)<1e-8);assert(Math.abs(spikeAngle(.17))<1e-8);assert.equal(playerLayout({spike:0}),LAYOUT);beginScenario("spike");tickScenario(1.2);assert(players.some(p=>p.spike>0));assert.equal(ball.x,435);tickScenario(.15);assert(ball.x>435);endScenario();console.log("PASS: spike back-to-front upper arc, exact final pose, timed ball contact.");`,context);

vm.runInContext(`beginScenario("spike");tickScenario(.4);const hitter=players.find(p=>p.approach);assert(hitter);assert(hitter.moving);assert.equal(playerLayout(hitter),APPROACH_LAYOUT);assert.equal(APPROACH_LAYOUT.find(p=>p.id==="arm-left").flip,true);assert(hitter.x>335&&hitter.x<435);tickScenario(.5);assert.equal(playerLayout(hitter),SPIKE_LAYOUT);endScenario();console.log("PASS: approach back-arm pose, run-up movement, transition to spike.");`,context);
vm.runInContext(`reset();ready=true;paused=false;scenario=null;$('mistakes').value='0';let count=0;while(!(ball.state==='flight'&&ball.touch===3)&&count++<2000)tick(1/60);assert(ball.touch===3);const attacker=ball.target,startX=attacker.x;let approachFrames=0,movingFrames=0;for(let i=0;i<90;i++){tick(1/60);if(approachingSpike(attacker)){approachFrames++;assert.equal(playerLayout(attacker),APPROACH_LAYOUT);if(attacker.moving)movingFrames++;}}assert(Math.abs(attacker.x-startX)>90);assert(approachFrames>45);assert(movingFrames>40);assert(attacker.spike>0);console.log('PASS: live rally run-up travels >90 pixels, rear-arm pose lasts >45 frames, jump starts after approach.');`,context);
vm.runInContext(`reset();ready=true;paused=false;scenario=null;const original=players.map(p=>p.zone);rotateTeam(0);assert(rotationMotion);tick(.8);assert(rotationMotion);tick(.8);assert.equal(rotationMotion,null);for(const p of players.filter(p=>p.team===0)){const g=formation(0,p.zone);assert.equal(p.x,g.x);assert.equal(p.y,g.y)}for(let i=0;i<5;i++){rotateTeam(0);tickRotation(2)}assert.deepEqual(players.map(p=>p.zone),original);const arrangements=[];for(const mode of ['serve','receive','attack','defend']){formationPreview=mode;arrangements.push(JSON.stringify(players.map(tacticalGoal)));for(const p of players){const g=tacticalGoal(p);assert(g.x>90&&g.x<910&&g.y>90&&g.y<530)}}assert.equal(new Set(arrangements).size,4);const formationScore=JSON.stringify(scores);tick(10);assert.equal(JSON.stringify(scores),formationScore);formationPreview=null;console.log('PASS: visible rotation transition, six rotations restore order, four distinct formations, preview does not score.');`,context);

vm.runInContext(`beginScenario("toss");tickScenario(.5);const setterT=players.find(p=>p.toss>0);assert(setterT);const poseT=playerLayout(setterT);assert.equal(poseT.length,5);assert(!poseT.some(p=>p.id.startsWith("sleeve-")));assert.equal(poseT.find(p=>p.id==="arm-left").rotation,90);assert.equal(poseT.find(p=>p.id==="arm-right").flip,true);tickScenario(1);assert.equal(playerLayout(setterT),LAYOUT);endScenario();console.log("PASS: imported toss pose, both bare arms visible, jersey sleeves excluded, normal pose restored.");`,context);
vm.runInContext(`reset();ready=true;paused=false;scenario=null;manualControl=true;const userP=players.find(p=>p.index===controlledIndex),ux=userP.x,uy=userP.y;heldKeys.add('KeyW');heldKeys.add('KeyA');updateManual(userP,.1);assert(Math.abs(Math.hypot(userP.x-ux,userP.y-uy)-21)<1e-8);heldKeys.clear();updateManual(userP,.1);assert(!userP.moving);ball={state:'flight',x:userP.x,y:userP.y,z:40};requestSpike();assert(userP.spike>0);updateManual(userP,.49);assert.equal(ball.kind,'attack');assert.equal(ball.target.team,1);const firstShot=ball;updateManual(userP,.01);assert.equal(ball,firstShot);manualControl=false;console.log('PASS: WASD normalized speed, stationary state, Space spike contact, opponent target, one hit per press.');`,context);

vm.runInContext(`const orderSpike=drawOrder({spike:.4,block:0,moving:false}).map(p=>p.id);for(const id of ["arm-right","sleeve-right","arm-left","sleeve-left"])assert(orderSpike.indexOf(id)>orderSpike.indexOf("shirt"));assert(orderSpike.indexOf("arm-left")>orderSpike.indexOf("sleeve-right"));assert.equal(drawOrder({spike:0,block:0}),LAYOUT);const drawnParts=[];for(const method of ["save","restore","translate","rotate","scale","beginPath","ellipse","fill","fillText"])ctx[method]=()=>{};ctx.drawImage=asset=>drawnParts.push(asset);sprites[0]=Object.fromEntries(LAYOUT.map(p=>[p.id,p.id]));drawPlayer({index:0,team:0,x:100,y:100,angle:0,zone:1,spike:.4,block:0,jump:.3,phase:0,moving:false});assert(drawnParts.includes("arm-left"));assert(drawnParts.includes("arm-right"));assert(drawnParts.indexOf("arm-left")>drawnParts.indexOf("shirt"));console.log("PASS: both skin arms drawn during stationary spike; striking arm and sleeve above torso, other poses unchanged.");`,context);
vm.runInContext(`reset();ready=true;paused=false;scenario=null;formationPreview=null;manualControl=true;heldKeys.clear();const actionP=players.find(p=>p.index===controlledIndex);actionP.x=300;actionP.y=310;heldKeys.add('KeyD');heldKeys.add('ShiftLeft');updateManual(actionP,.1);assert(actionP.approach);assert.equal(playerLayout(actionP),APPROACH_LAYOUT);assert.equal(actionP.x,327);requestSpike();assert(!actionP.approach);const spikeStart=actionP.manualSpike;requestSpike();assert.equal(actionP.manualSpike,spikeStart);requestToss();assert(!(actionP.manualToss>0));heldKeys.clear();updateManual(actionP,.7);for(const [key,axis,sign]of [['KeyW','y',-1],['KeyS','y',1],['KeyA','x',-1],['KeyD','x',1]]){actionP.x=300;actionP.y=310;heldKeys.clear();heldKeys.add(key);ball={state:'flight',x:300,y:310,z:30};requestToss();assert(actionP.toss>0);assert(!playerLayout(actionP).some(p=>p.id.startsWith('sleeve-')));updateManual(actionP,.15);assert.equal(Math.sign(ball[axis==='x'?'targetX':'targetY']-actionP[axis]),sign);const once=ball;updateManual(actionP,.15);assert.equal(ball,once);updateManual(actionP,.3);}heldKeys.clear();manualControl=false;console.log('PASS: Shift run-up pose, action lock, four directional tosses, hidden toss sleeves, single contact per action.');`,context);
vm.runInContext(`reset();ready=true;paused=false;scenario=null;manualControl=true;heldKeys.clear();const strikeP=players.find(p=>p.index===controlledIndex);const feeder=players.find(p=>p.team===0&&p!==strikeP);launch(feeder,strikeP,1,'pass');ball.x=strikeP.x;ball.y=strikeP.y+20;ball.z=30;ball.t=ball.duration-.02;ball.manualFeed=true;requestSpike();assert.equal(ball.strikeOwner,strikeP.index);for(let i=0;i<31;i++)tick(1/60);assert.equal(ball.kind,'attack');assert.equal(ball.target.team,1);assert(strikeP.manualContact);reset();manualControl=true;const sp=players.find(p=>p.index===controlledIndex);while(sp.zone!==1)rotateTeam(0);rotationMotion=null;servingTeam=0;serve();assert(serviceGame);assert.equal(serviceGame.phase,'aim');const sx=serviceGame.aimX;heldKeys.add('KeyD');tick(.1);heldKeys.clear();assert(serviceGame.aimX>sx);advanceServiceGame();assert.equal(serviceGame.phase,'power');serviceGame.meter=.7;advanceServiceGame();assert.equal(serviceGame.phase,'timing');serviceGame.meter=.5;advanceServiceGame();assert.equal(serviceGame,null);assert.equal(ball.kind,'serve');assert.equal(ball.miss,false);startServiceGame();advanceServiceGame();serviceGame.meter=.1;advanceServiceGame();serviceGame.meter=.9;advanceServiceGame();assert.equal(ball.pointWinner,1);assert(ball.miss);for(let i=0;i<250;i++)tick(1/60);assert(scores[1]>0);manualControl=false;console.log('PASS: late Space spike survives landing, automatic service turn, WASD aim, power/timing phases, successful serve, fault scores for opponent.');`,context);
