const assert=require('assert'),R=require('./league-rules.js');
assert.deepEqual(R.config.matchDays,[4,9,14,19,24]);assert.equal(R.schedule().length,20);const pairs=new Set();for(const m of [...R.history(),...R.schedule()]){const key=[m.home,m.away].sort().join(':');pairs.add(key)}assert.equal(pairs.size,28);
for(const day of R.config.matchDays){const games=R.fixtures(day);assert.equal(games.length,4);assert.equal(new Set(games.flatMap(m=>[m.home,m.away])).size,8)}for(const day of [0,1,2,7,13,98])assert.equal(R.fixtures(day).length,0);
let state=R.normalize(null),own=R.standings(state).find(r=>r.id===0);assert.equal(own.rank,8);assert.equal(own.losses,3);assert.equal(own.points,0);assert.equal(R.progress(state).played,0);
const ours=R.schedule().filter(m=>m.ours);for(const [i,m] of ours.entries()){assert(R.record(state,m.id,m.home===0?[25,18]:[18,25]));R.settleRounds(state);assert.equal(R.progress(state).played,i+1);assert.equal(R.progress(state).prologueComplete,i===4)}assert(R.complete(state,24));assert.equal(state.completedDay,24);assert(R.progress(state).rescued);assert(R.progress(state).standingsFinal);assert(R.standings(state).every(r=>r.played===8));assert.equal(R.standings(state).reduce((n,r)=>n+r.points,0),96);const snapshot=JSON.stringify(state);assert(!R.settleRounds(state));assert(!R.complete(state,25));assert.equal(JSON.stringify(state),snapshot);assert.deepEqual(R.normalize(JSON.parse(snapshot)),state);assert(!R.record(state,'invalid',[25,10]));assert(!R.record(state,ours[0].id,[25,25]));
state=R.normalize(null);for(const m of ours){R.record(state,m.id,m.home===0?[18,25]:[25,18]);R.settleRounds(state)}assert(R.progress(state).prologueComplete);assert(!R.progress(state).rescued);assert.equal(R.progress(state).rank,8);
state=R.normalize(null);assert(R.importOwn(state,{7:[25,18],14:[19,25]}));assert.equal(R.progress(state).played,2);assert(!R.importOwn(state,{7:[25,18],14:[19,25]}));const old={version:1,results:{'r1-0-7':[25,18],'r2-6-0':[25,19],'r14-4-0':[25,20]}};state=R.normalize(old);assert.equal(R.progress(state).played,2);assert.deepEqual(state.legacyResults,old.results);assert.deepEqual(R.normalize(state),state);
console.log('PASS: 8th-place takeover, 3 historical losses, 5 remaining games/24 days, honest success/failure, score validation and archived legacy results.');

const migrated=R.normalize({version:2,results:{'rescue1-0-7':[25,19],'rescue2-6-0':[20,25]}});assert.equal(R.progress(migrated).played,2);assert.equal(R.progress(migrated).next.day,14);const dated=R.normalize(null);R.importOwn(dated,{3:[25,19],6:[25,20],9:[19,25]});assert.equal(R.progress(dated).played,3);const modern=R.normalize(null);R.importOwn(modern,{version:3,'rescue3-0-5':[25,18],14:[25,18]});assert.equal(R.progress(modern).played,1);assert.deepEqual(modern.results['rescue3-0-5'],[25,18]);console.log('PASS: previous short-season saves and dated legacy scores migrate without day-14/round-2 collisions.');

const oldComplete=R.normalize({version:3,results:Object.fromEntries(ours.slice(0,4).map(m=>[m.id,m.home===0?[15,8]:[8,15]])),completionSeen:true,completedDay:19});assert.equal(R.progress(oldComplete).played,4);assert.equal(R.progress(oldComplete).prologueComplete,false);assert.equal(oldComplete.completionSeen,false);assert.equal(oldComplete.completedDay,null);assert.equal(R.progress(oldComplete).next.day,24);
const RR=require('./room-rules.js'),wallet=RR.defaults(),last=ours[4];assert.equal(RR.matchReward(wallet,last.id,5),1000);const restored=RR.normalize(wallet);assert.equal(RR.matchReward(restored,last.id,5),0);assert.equal(restored.matchRewards.length,1);console.log('PASS: four-game saves retain results and reopen fifth match; fifth reward survives reload without duplicates.');
