const assert=require('assert'),R=require('./league-rules.js'),T=require('./team-rules.js'),fs=require('fs'),vm=require('vm');
const pairs={};for(let week=1;week<=14;week++){const fixtures=R.fixtures(week*7);assert.equal(fixtures.length,4);assert.equal(new Set(fixtures.flatMap(m=>[m.home,m.away])).size,8);assert.equal(fixtures.filter(m=>m.ours).length,1);assert.equal(R.dateFor(week*7).getUTCDay(),0);for(const m of fixtures){const key=m.home+':'+m.away;pairs[key]=(pairs[key]||0)+1}}
assert.equal(Object.keys(pairs).length,56);assert(Object.values(pairs).every(n=>n===1));for(let i=1;i<500;i++)assert.equal(R.dayFor(R.dateFor(i)),i);for(const d of [-7,0,1,99,105,196,7.5])assert.equal(R.fixtures(d).length,0);
let state=R.normalize(null);assert(R.standings(state).every(r=>r.played===0&&r.rank===null));assert(!R.progress(state).prologueComplete);const legacy={};for(let week=1;week<=13;week++)legacy[week*7]=week%2?[25,18]:[19,25];assert(R.importOwn(state,legacy));assert(R.settleRounds(state));assert(!R.progress(state).prologueComplete);assert.equal(R.progress(state).reported,52);assert(R.standings(state).every(r=>r.played===13));assert.equal(R.standings(state).find(r=>r.id===0).wins,7);assert.equal(R.standings(state).find(r=>r.id===0).points,21);assert(!R.complete(state,1000));
const last=R.fixtures(98).find(m=>m.ours);assert(R.record(state,last.id,last.home===0?[25,17]:[17,25]));R.settleRounds(state);assert(R.complete(state,98));assert.equal(state.completedDay,98);assert(R.progress(state).prologueComplete);assert(R.progress(state).standingsFinal);assert.equal(R.progress(state).next,null);assert(R.standings(state).every(r=>r.played===14));assert.equal(R.standings(state).reduce((n,r)=>n+r.points,0),56*3);
const saved=JSON.stringify(state);assert(!R.settleRounds(state));assert(!R.complete(state,99));assert.equal(JSON.stringify(state),saved);assert.deepEqual(R.normalize(JSON.parse(saved)),state);assert(!R.record(state,last.id,[25,25]));assert(!R.record(state,last.id,[0,0]));assert(!R.record(state,'missing',[25,10]));assert(!R.record(state,last.id,[1,999]));assert.equal(JSON.stringify(state),saved);
const invalid=R.normalize({completedDay:99,results:{[last.id]:[25,25]}});assert(!R.progress(invalid).prologueComplete);R.complete(invalid,99);assert.equal(invalid.completedDay,null);const deterministic=R.normalize(null);R.importOwn(deterministic,legacy);R.settleRounds(deterministic);for(const f of R.schedule().filter(f=>f.day<98))assert.deepEqual(deterministic.results[f.id],state.results[f.id]);
const a=T.generate(),b=T.generate();assert(T.valid(a)&&T.valid(b));assert.notDeepEqual(a,b);const stored={};function load(){const c={CampRules:require('./camp-rules.js'),localStorage:{getItem:k=>stored[k],setItem:(k,v)=>stored[k]=v}};vm.createContext(c);vm.runInContext(fs.readFileSync('team-rules.js','utf8'),c);return JSON.stringify(c.TeamRules.players)}assert.equal(load(),load());
console.log('PASS: finite 8-club/14-round/56-match home-away league, orientation, standings, deterministic temporary results, result validation, save migration, idempotent completion and no new season.');
