const assert=require('assert'),fs=require('fs'),vm=require('vm'),logic=require('./menu-state.js');
let s=logic.normalize(null);for(let i=0;i<99;i++)s=logic.advance(s).state;assert.deepStrictEqual(s,{day:1,clicksToday:99});let r=logic.advance(s);assert(r.completed);assert.deepStrictEqual(r.state,{day:2,clicksToday:0});assert.equal(logic.advance({day:3,clicksToday:99}).matchDay,true);assert.equal(logic.advance({day:4,clicksToday:99}).matchDay,false);assert.deepStrictEqual(logic.normalize({day:-5,clicksToday:200}),{day:1,clicksToday:0});
class Node{constructor(){this.children=[];this.style={};this.attrs={};this.events={};this.open=false;this.lastChild={textContent:''};this.classes=new Set();this.classList={add:x=>this.classes.add(x),remove:x=>this.classes.delete(x),contains:x=>this.classes.has(x)};}setAttribute(k,v){this.attrs[k]=v}append(...a){this.children.push(...a);for(const n of a)n.parent=this}replaceChildren(...a){this.children=[];this.append(...a)}addEventListener(e,f){this.events[e]=f}getBoundingClientRect(){return{height:620,top:0}}remove(){this.parent.children=this.parent.children.filter(x=>x!==this)}showModal(){this.open=true;this.openCount=(this.openCount||0)+1}close(){this.open=false;this.events.close?.()}focus(){this.focused=true}querySelector(){return this.status??=new Node()}}
const nodes={},tiers=Array.from({length:5},(_,i)=>{const n=new Node();n.dataset={floor:String(i===1?0:i+1)};n.connector=new Node();n.connector.getBoundingClientRect=()=>({top:60+i*110,height:2});n.status=new Node();n.querySelector=sel=>sel==='.connector'?n.connector:n.status;return n});let applied=0;let clock=0;const stored={};const context={MenuState:logic,RoomSystem:{onClick(){return {ap:4}},applyGain(){applied++}},console,Set,performance:{now:()=>clock},localStorage:{getItem:k=>stored[k]??null,setItem:(k,v)=>stored[k]=v},window:{matchMedia:()=>({matches:false}),addEventListener(){}},document:{getElementById:id=>nodes[id]??=new Node(),querySelectorAll:()=>tiers,querySelector:sel=>nodes[sel]??=new Node(),createElement:()=>new Node()},requestAnimationFrame:()=>1,setTimeout:()=>1,clearTimeout(){}};vm.createContext(context);vm.runInContext(fs.readFileSync('menu.js','utf8'),context);
for(let i=0;i<100;i++)nodes.energyButton.events.click();assert.equal(applied,0);vm.runInContext('animate(100)',context);assert.equal(applied,0);assert.equal(nodes.mobileDay.textContent,'2. gün');assert.equal(nodes.mobileCount.textContent,0);assert.equal(nodes.mobileDay.textContent,"2. gün");assert.equal(nodes.pulseLayer.children.length,100);vm.runInContext('animate(1800)',context);assert.equal(applied,100);assert.equal(nodes.pulseLayer.children.length,0);assert(tiers.every(n=>n.classList.contains('energized')));assert.equal(nodes.mobileDay.textContent,'2. gün');vm.runInContext('animate(2500)',context);assert(tiers.every(n=>!n.classList.contains('energized')));for(let i=0;i<500;i++)nodes.energyButton.events.click();assert.equal(nodes.mobileDay.textContent,'7. gün');assert(nodes.matchDialog.open);assert.equal(nodes.matchDialog.openCount,1);nodes.laterMatch.events.click();assert(!nodes.matchDialog.open);assert(nodes.energyButton.focused);for(let i=0;i<100;i++)nodes.energyButton.events.click();assert.equal(nodes.weekLabel.textContent,'HAFTA 02');assert.equal(JSON.parse(stored['idle-spiker-main-menu-v1']).day,8);assert.equal(nodes.calendar.children.length,7);
const html=fs.readFileSync('index.html','utf8');for(const m of html.matchAll(/(?:src|href)="([^"]+)"/g))if(!m[1].startsWith('#'))assert(fs.existsSync(m[1].split('?')[0]),'Missing link: '+m[1]);new Function(fs.readFileSync('menu.js','utf8'));console.log('PASS: exact 100-click day, 700 rapid clicks without loss, one pulse per click, all five floor crossings, pulse cannot advance calendar, match popup/close, week rollover, persistence, links.');
for(let i=0;i<50;i++)nodes.energyButton.events.click();const active=nodes.calendar.children.find(n=>n.attrs['aria-current']==='date');assert.equal(active.attrs['aria-valuenow'],50);assert.equal(active.children[0].style.height,'50%');assert(!html.includes('class="day-card"'));assert(html.includes('<h2>Takvim</h2>'));console.log('PASS: active calendar cell fills to 50%, standalone progress panel removed.');



vm.runInContext('pulses.splice(0).forEach(p=>p.node.remove());addPulse("auto")',context);
const pulse=vm.runInContext('pulses[0]',context);assert.equal(vm.runInContext('pulses.length',context),1);assert.equal(pulse.node.className,'energy-pulse auto-pulse');assert.equal(pulse.originX,21);assert.equal(pulse.originY,0);
vm.runInContext('animate(1800)',context);assert(tiers.every(t=>t.classes.has('energized')));assert.equal(vm.runInContext('pulses.length',context),0);assert(pulse.node.style.transform.startsWith('translate(0px,'));
console.log('PASS: automatic pulse uses the manual vertical path and reaches every floor.');
