const assert=require('assert'),C=require('./camp-rules.js'),R=require('./room-rules.js');
const players=Array.from({length:5},(_,i)=>({id:'player-'+i,spike:98}));let s=R.defaults();s.ap=10000;s.budget=10000;
assert(!C.update(s,players,1).announced);assert(!C.enroll(s,players[0],20));assert.equal(C.cap(s,players[0]),50);
s.stage='bal';players[0].spike=97;assert(!C.update(s,[players[0]],10).announced);players[0].spike=98;assert(C.update(s,players,10).announced);assert.equal(s.camp.opensDay,17);const before=JSON.stringify(s);assert(!C.enroll(s,players[0],16));assert.equal(JSON.stringify(s),before);
C.update(s,players,17);let ap=s.ap,cash=s.budget;assert(C.enroll(s,players[0],17));assert.equal(s.ap,ap-1200);assert.equal(s.budget,cash-500);assert.equal(s.camp.entries[0].endDay,24);assert.equal(C.cap(s,players[0]),100);assert(!C.enroll(s,players[0],17));assert(C.enroll(s,players[1],17));assert(C.enroll(s,players[2],17));assert(!C.enroll(s,players[3],17));
s=R.normalize(JSON.parse(JSON.stringify(s)));assert.equal(C.update(s,players,23).completed.length,0);assert.equal(C.update(s,players,24).completed.length,3);assert.equal(C.cap(s,players[0]),105);assert.equal(C.cap(s,players[3]),100);assert.equal(players[0].spike,98);assert.equal(C.update(s,players,24).completed.length,0);assert.equal(C.update(s,players,20).completed.length,0);assert.equal(s.camp.lastDay,24);assert(!C.enroll(s,players[0],24));players[0].spike=103;assert.deepEqual(C.price(s,players[0]),{ap:2400,cash:1000});assert(C.enroll(s,players[0],24));C.update(s,players,31);assert.equal(C.cap(s,players[0]),110);assert(!C.enroll(s,players[0],31));
s=R.defaults();s.stage='bal';C.update(s,players,1);C.update(s,players,8);for(const [ap,cash] of [[1199,500],[1200,499],[0,0]]){s.ap=ap;s.budget=cash;const before=JSON.stringify(s);assert(!C.enroll(s,players[3],8));assert.equal(JSON.stringify(s),before)}
s.stage='prologue';assert.equal(C.cap(s,players[0]),50);assert(!C.enroll(s,players[3],8));assert.equal(C.normalize({entries:[{playerId:'x',startDay:1,targetBoost:99}]}).entries.length,0);
console.log('PASS: BAL-only near-cap announcement, 7-day registration wait, atomic two-currency payment, 3 slots, 7-day completion, personal +5 cap, no stat gifts or duplicate rewards, reload and rollback.');
