const fs=require('fs');const pose=JSON.parse(fs.readFileSync('C:/Users/MELİH BEY/Downloads/uc-parca-yerlesimi (4).json','utf8'));if(pose.parts.length!==7)throw Error('Invalid pose');fs.writeFileSync('onaylanan-spike-yerlesimi.json',JSON.stringify(pose,null,2));let s=fs.readFileSync('build-match.cjs','utf8');s=s.replace('const assets={};',"const spikeLayout=JSON.parse(fs.readFileSync('onaylanan-spike-yerlesimi.json','utf8')).parts;\nconst assets={};").replace(".replace('__BLOCK_LAYOUT__',JSON.stringify(blockLayout))",".replace('__BLOCK_LAYOUT__',JSON.stringify(blockLayout)).replace('__SPIKE_LAYOUT__',JSON.stringify(spikeLayout))");fs.writeFileSync('build-match.cjs',s);
s=fs.readFileSync('match-template.html','utf8');s=s.replace('BLOCK_LAYOUT=__BLOCK_LAYOUT__,','BLOCK_LAYOUT=__BLOCK_LAYOUT__,SPIKE_LAYOUT=__SPIKE_LAYOUT__,');s=s.replace('function playerLayout(p){return p.block>0?BLOCK_LAYOUT:LAYOUT}',`function spikeAngle(remaining){const age=.65-remaining;if(age<.3)return -Math.PI;const u=clamp((age-.3)/.18,0,1);return -Math.PI*(1-u*u*(3-2*u))}
function playerLayout(p){return p.block>0?BLOCK_LAYOUT:p.spike>0?SPIKE_LAYOUT:LAYOUT}`);
s=s.replace("if(part.id.startsWith('arm-')&&!p.moving&&!(p.block>0))continue;","if(part.id.startsWith('arm-')&&!p.moving&&!(p.block>0)&&!(p.spike>0&&part.id==='arm-left'))continue;");
s=s.replace('if(isArm&&!(p.block>0)){',`if(p.spike>0&&!(p.block>0)&&(part.id==='arm-left'||part.id==='sleeve-left')){const shoulder=SPIKE_LAYOUT.find(q=>q.id==='sleeve-left'),cx=shoulder.x+shoulder.width*shoulder.scale*shoulder.pivotX,cy=shoulder.y+shoulder.height*shoulder.scale*shoulder.pivotY;ctx.translate(cx,cy);ctx.rotate(spikeAngle(p.spike));ctx.translate(-cx,-cy)}else if(isArm&&!(p.block>0)&&!(p.spike>0)){`);
s=s.replace('p.block=Math.max(0,(p.block||0)-dt);','p.block=Math.max(0,(p.block||0)-dt);p.spike=Math.max(0,(p.spike||0)-dt);');s=s.replace('ball.t+=dt;const t=Math.min(1,ball.t/ball.duration);',`ball.t+=dt;if(ball.touch===3&&!ball.miss&&!ball.spikePrepared&&ball.t>=ball.duration-.3){ball.spikePrepared=true;ball.target.spike=.65;ball.target.jump=.5;}const t=Math.min(1,ball.t/ball.duration);`);s=s.replace("if(t===1){if(ball.miss", "if(t===1){if(ball.touch===3&&!ball.miss&&ball.target.spike>.17)return;if(ball.miss");s=s.replace('else{receiver.jump=.5;const defenders=', 'else{const defenders=');
s=s.replace('p.block=0;p.angle=', 'p.block=0;p.spike=0;p.angle=');
const a=s.indexOf(" if(scenario.kind==='spike'){"),b=s.indexOf('\n',a);s=s.slice(0,a)+` if(scenario.kind==='spike'){hitter.x=435;hitter.y=260;receiver.x=790;receiver.y=340;if(t>=.35&&t<1){hitter.spike=.65-(t-.35);hitter.jump=.5*(1-(t-.35)/.65);hitter.hit=.3;}previewArc(hitter,receiver,(t-.83)/1.1,45);}`+s.slice(b);
fs.writeFileSync('match-template.html',s);
let test=fs.readFileSync('test-match.cjs','utf8').replace("if(part.id.startsWith('arm-')&&!p.moving&&!(p.block>0))continue;","if(part.id.startsWith('arm-')&&!p.moving&&!(p.block>0)&&!(p.spike>0&&part.id==='arm-left'))continue;");test+='\nvm.runInContext(`assert.equal(playerLayout({spike:.5}),SPIKE_LAYOUT);assert.equal(spikeAngle(.65),-Math.PI);assert(Math.abs(spikeAngle(.26)+Math.PI/2)<1e-8);assert(Math.abs(spikeAngle(.17))<1e-8);assert.equal(playerLayout({spike:0}),LAYOUT);beginScenario("spike");tickScenario(.75);assert(players.some(p=>p.spike>0));assert.equal(ball.x,435);tickScenario(.15);assert(ball.x>435);endScenario();console.log("PASS: spike back-to-front upper arc, exact final pose, timed ball contact.");`,context);\n';fs.writeFileSync('test-match.cjs',test);
